liquid newton upgrade
autonity/autonity pull request #1015
Opened 2024-06-20 08:06 UTC by tbssajal

- Moved all the logic to LiquidLogic.sol
- Using fallback to delegate call from LiquidState.sol to LiquidLogic.sol
- Kept all simple view only function implementaion in LiquidState.sol except any function that requires complex logic or computation, using static call for the complex ones.

2024-08-19 15:24 UTC, lorenzo-dev1 requested changes
Some change request and comments here and there, but I think the  delegation approach is solid!

2024-08-21 09:10 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +    Autonity private autonityContract; //not hardcoded for testing purposes
I did not see such issue, but I can try to add a test.

2024-08-21 09:11 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +    // storage layout - this must be compatible with LiquidLogic
>What about separating the genesis storage layout in a separate contract? Then both liquid state and liquic logic can inherit that contract, therefore we are sure that the initial layout is the same between the two contracts.

That's a good idea.

>I wonder however what happens if then we add some new storage variables in the liquid logic. Would that work?

That should work. In fact there are some new variables in liquid logic I guess.

2024-08-21 09:17 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +        liquidLogicContract = address(new LiquidLogic());
I did this way because it is easier, no particular reason in my mind. However I think it would be a bit difficult to deploy it separately, because in constructor of Autonity, bonding opperation happens. So LiquidLogic needs to be deployed first. But then LiquidLogic needs to address of Autonity contract. Although we have the autonity address hardcoded so maybe we can use that.

2024-08-21 09:20 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +        address payable liquidStateContract;
I made the type `address` because there was not much use of `LiquidState` the contract no function to call like before. To call any function I had to cast it to `address` type. The reason to make `address payable` is because of payable fallback functions.

2024-08-21 09:24 UTC, tbssajal commented on accounts/abi/bind/template.go
> +
Basically I copied and combined them from two type of functions in this template file: 1. view only functions, 2. functions that mutate state.
I wanted to provide a way to call a function that can mutate the state but then the state is reverted and we only get the return values from that function. It is to mimic the `function.call` from truffle tests where `function` can be any solidity function and yet the state is not changed. Instead it returns the values after the `function` is executed. So I copied the parts from the template where a function is called and it mutate states and then extracted the return values and reverted the state.

2024-08-21 09:26 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +            require(liquidLogicContract != address(0), "liquid logic contract not deployed");
Yeah it should never happen. But if it does happen, then the call would revert at genesis or when registering a new validator. In both cases, it is a safe point to revert and investigate. So I added it.

2024-08-21 09:30 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +        require(_commissionRate <= LiquidLogic(payable(_liquidLogicAddress)).COMMISSION_RATE_PRECISION());
Actually it was present already. I did not modify it. `COMMISSION_RATE_PRECISION()` is a constant in LiquidLogic.sol so we cannot upgrade it unless we make it a variable.

2024-08-21 09:33 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +            }
Yeah it could happen due to bug or if the LiquidLogic does not support the method or there is no LiquidLogic contract. I am not sure if I should keep it or remove it so I just kept it to be safe.

2024-08-21 09:34 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +            }
Correct. But once https://github.com/autonity/autonity/pull/1007 gets merged, we don't need to think about notifying anyone. So it will be just return.

2024-08-21 09:37 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +                abi.encodeWithSignature("unlock(address,uint256)", _unbonding.delegator, _liquidAmount)
Good idea. Let me think about how to do it. Maybe some complex mapping will require.

2024-08-21 09:44 UTC, tbssajal commented on autonity/solidity/contracts/LiquidLogic.sol
>          autonityContract = IERC20(msg.sender);
You are right, the state of liquid logic contract does not matter. And when a delegate call is done, this value won't matter.

2024-08-21 09:45 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +        liquidLogicContract = address(new LiquidLogic());
I did this way because it is easier, no particular reason in my mind.

2024-08-21 09:47 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +            require(liquidLogicContract != address(0), "liquid logic contract not deployed");
For example if we deploy LiquidLogic separately at genesis instead of deploying at autonity contract constructor. This check would be useful. It would ensure that LiquidLogic is already deployed.

2024-08-21 09:50 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +    }
Yeah but right now the gas is paid by user. If we keep the address in state contract and use some "push" update, the gas will be paid by us (or none, which is not desirable I guess).

2024-08-21 09:52 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +}
Thanks. I will try to give it a read. But the only reason I did it is to have them as view only, which is useful for testing and also for users if they use bindings to make such calls.

2024-08-21 09:57 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +    }
> Meaning can we make this function go through the same flow as the others (fallback and delegate to the logic contract)?

We can but we cannot treat it as view only. Then to get unclaimed rewards without paying gas, we will have to do something like this: https://github.com/autonity/autonity/pull/1015#discussion_r1724736326. Let me which way you think is the best.

2024-08-21 12:18 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/LiquidState.sol
> +    // storage layout - this must be compatible with LiquidLogic
so there are some variables in LiquidLogic that are not present in LiquidState?

2024-08-21 12:25 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/LiquidState.sol
> +    Autonity private autonityContract; //not hardcoded for testing purposes
would be good to check indeed

2024-08-21 12:28 UTC, lorenzo-dev1 commented on accounts/abi/bind/template.go
> +
oh ok, so this is for testing only I guess?

2024-08-21 12:30 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/LiquidState.sol
> +        require(_commissionRate <= LiquidLogic(payable(_liquidLogicAddress)).COMMISSION_RATE_PRECISION());
I think we can if we upgrade the entire LiquidLogic contract right? Since we substitute the bytecode

2024-08-21 12:30 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Autonity.sol
> +            }
I think it is good to keep

2024-08-21 12:45 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/LiquidState.sol
> +    }
You mean that a user trying to get his unclaimed rewards will need to pay gas (even if no state is modified?). And this is due to the indirection layer we introduced?

2024-08-21 13:20 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +    // storage layout - this must be compatible with LiquidLogic
Actually having any state variables would not work maybe. But we don't have any new state variables, but some constants. 
```
uint256 public constant FEE_FACTOR_UNIT_RECIP = 1_000_000_000;
uint256 public constant COMMISSION_RATE_PRECISION = 10_000;
```

2024-08-21 13:22 UTC, tbssajal commented on accounts/abi/bind/template.go
> +
Yeah, for now. But we can also use something like to mimic the rpc call "eth_call" which run any contract function and returns the gas and/or values.

2024-08-21 13:23 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +        require(_commissionRate <= LiquidLogic(payable(_liquidLogicAddress)).COMMISSION_RATE_PRECISION());
Right, if we upgrade the contract. But then already deployed liquid state contract will not be checked. Only the new ones.

2024-08-21 14:38 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +    }
Yeah

2024-08-22 09:02 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +    }
The thing I kept in mind writing this function is that the logic is done in LiquidLogic contract and all the inputs are passed from Liquidstate contract. I guess, if we want to upgrade LiquidLogic, we can keep the function signature same, unless we update the state variables layout as well. In case we need to update the state variables layout, we have to update all LiquidState contracts as well.

2024-08-22 10:57 UTC, tbssajal commented on autonity/solidity/contracts/LiquidLogic.sol
>          autonityContract = IERC20(msg.sender);
removed

2024-08-22 10:57 UTC, tbssajal commented on autonity/solidity/contracts/LiquidLogic.sol
> +    function redistribute(uint256 _ntnReward) external payable onlyAutonity returns (uint256, uint256) {
done

2024-08-22 10:58 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +                abi.encodeWithSignature("unlock(address,uint256)", _unbonding.delegator, _liquidAmount)
Done. Btw I had to add separate function for each call. Not sure if there is a better way to do it.

2024-08-22 12:04 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Autonity.sol
> +                accounts[_bonding.delegator] += _bonding.amount;
Is this new? I don't see a corresponding deletion so I assume it was missing before?

2024-08-22 12:32 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/LiquidState.sol
> +    }
Ok, let's see what other think about it.

2024-08-22 12:36 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +                accounts[_bonding.delegator] += _bonding.amount;
Yes I missed it before. Apparently there is no tests for these types of behaviour assuming they won't happen.

2024-08-22 13:08 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +        require(_commissionRate <= LiquidLogic(payable(_liquidLogicAddress)).COMMISSION_RATE_PRECISION());
In that case we will have to use a variable instead of a constant. I guess it is fine this way, if we don't want to update the constant anyway.

2024-08-22 13:18 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +    // storage layout - this must be compatible with LiquidLogic
It should work but my guess is they would have 0 value in them. Because the slots are assigned sequentially to the state variables. So in the storage of a state contract, the slot address should be greater than all of its variables.

2024-08-27 06:48 UTC, Jason-Zhangxin-Chen commented on accounts/abi/bind/template.go
> +	{{range .Transacts}}
I can understand that this is for testing only, to get the writer function execution results without state changes after that. It would be better to add more detail comment for the purpose to help the others to understand it better.

2024-08-27 07:07 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
> +    /**
It would be better to add comment that now we just share the same instance of logic contract, and regarding the state contract, each validtor has their own instance. This new structure look great!

2024-08-27 08:11 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +        liquidLogicContract = address(new LiquidLogic());
Because the deployer is the autonity contract, it cannot conflict with other protocol contracts deployed by the operator.

> Do we need to reserved an address for this logic contract in the protocol contract list?

Cannot comment on this. But if we need we can get the address from autonity contract directly.

2024-08-27 09:04 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/LiquidState.sol
> +        require(_commissionRate <= LiquidLogic(payable(_liquidLogicAddress)).COMMISSION_RATE_PRECISION());
Is it better to create a common contract to store all the constants of the protocol? Thus we can reduce the dependencies circles in this feature?

2024-08-27 09:11 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/LiquidState.sol
> +    }
I think it is a good time to think about if we need a common protocol parameter contract that contains constants and variables settings for the protocol.

2024-08-27 12:43 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/LiquidState.sol
> +    fallback() payable external {
QQ: I am not familiar with solidity, what does this fallback() and receive() function do in solidity?

2024-08-27 12:46 UTC, Jason-Zhangxin-Chen reviewed
The approach look good to me. Just left few comments.

2024-08-27 14:18 UTC, tbssajal commented on autonity/solidity/contracts/LiquidLogic.sol
> +contract LiquidLogic is IERC20, LiquidStorage {
So the storage layout of both LiquidState and LiquidLogic needs to be same because we are doing delegate call from LiquidState to LiquidLogic. ([Original idea](https://github.com/autonity/autonity/pull/1015#discussion_r1715083414) from Lorenzo) Keeping all the state variables in LiquidStorage and inheriting it from both logic and state contract makes the storage layout same in both contracts.

2024-08-27 14:22 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +    fallback() payable external {
In short, fallback is executed if no other function matches the call data. Receive is executed when calldata is empty. Here are the docs for [fallback](https://docs.soliditylang.org/en/v0.7.2/contracts.html#fallback-function) and [receive](https://docs.soliditylang.org/en/v0.7.2/contracts.html#receive-ether-function).

2024-08-27 15:01 UTC, tbssajal commented on autonity/solidity/contracts/LiquidState.sol
> +        require(_commissionRate <= LiquidLogic(payable(_liquidLogicAddress)).COMMISSION_RATE_PRECISION());
> Thus we can reduce the dependencies circles in this feature?

I am not sure what you mean. Only LiquidState contract is dependant on LiquidLogic, so there shouldn't be any dependency circle.

> Is it better to create a common contract to store all the constants of the protocol?

That could be a good approach to put all the contants in one place.

2024-08-28 13:25 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +    /**
Added some more comments.

2024-08-30 05:39 UTC, tbssajal commented
Please approve the PR if no more changes are required. I will need to make some changes in https://github.com/autonity/autonity/pull/1007 after this one is approved.

2024-08-30 13:02 UTC, tbssajal commented
> Please approve the PR if no more changes are required. I will need to make some changes in #1007 after this one is approved.

hold it please.

2024-08-30 16:32 UTC, tbssajal commented
Please see the latest changes.

2024-09-03 08:38 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +    uint256 public maxRewardsDistributionGas = 20_000;
Nope. Youssef suggested they should not be too high. And I think it should be as minimum as possible, otherwise it gives some external contract too much gas to spend. Anyways we won't need them after https://github.com/autonity/autonity/pull/1007 is merged.

2024-09-03 10:17 UTC, tbssajal commented on autonity/solidity/contracts/vesting/LiquidRewardManager.sol
> -        if (address(liquidInfo[_validator].liquidContract) == address(0)) {
Let me check that.

2024-09-03 10:26 UTC, tbssajal commented on autonity/solidity/contracts/vesting/LiquidRewardManager.sol
> -        if (address(liquidInfo[_validator].liquidContract) == address(0)) {
You are right.

2024-09-03 10:35 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +    uint256 public maxRewardsDistributionGas = 20_000;
But I have added tests named `TestBondingGasConsumption` and `TestUnbondingGasConsumption` stakable_vesting_test.go file to check if the values are enough for vesting contract.

2024-09-03 10:39 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +    function SetLiquidLogicContract(address _contract) public virtual onlyOperator {
done

2024-09-03 10:39 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +                    (bool _sent, bytes memory _returnData) = _val.treasury.call{value: _atnSelfReward, gas: 2300}("");
done

2024-09-03 14:40 UTC, lorenzo-dev1 approved these changes
LGTM, I left two additional comments which I think would further improve the PR but it is already very good and suitable for merge

2024-09-03 14:40 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/liquid/LiquidLogic.sol
> +    function balanceOf(address _delegator) external view returns (uint256) {
Is it possible to make all the methods in LiquidLogic virtual? it would make the upgrade process easier.

2024-09-03 14:41 UTC, tbssajal commented on autonity/solidity/contracts/liquid/LiquidLogic.sol
> +    function balanceOf(address _delegator) external view returns (uint256) {
Sure, no problem.

2024-09-05 00:38 UTC, yazzaoui approved these changes
LGTM. Good work!

2024-09-05 08:05 UTC, merged