[WIP] Epoch head patch2
autonity/autonity pull request #1022
Opened 2024-07-08 09:15 UTC by Jason-Zhangxin-Chen

2024-07-26 14:15 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/fault_detector.go
> +		return false
Unless I am missing something, this scenario still cannot happen

2024-07-26 14:19 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/fault_detector.go
> +	}
I think this should never happen as normally we do not send future height msgs to the fault detector

2024-07-26 14:19 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/fault_detector.go
> +	}
I think this should never happen as normally we do not send future height msgs to the fault detector

2024-07-26 14:21 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/fault_detector.go
>  	}
I think this shoudln't happen since we do not send future height messages to the fault detector. I think this function should not return an error, since we should always be capable of computing the proposer of a non-future msg. Moreover right now if we return an error, the `isProposerValid` will return false and push a misbheaviour proof on-chain, which I don't think is correct.

2024-07-26 14:30 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/innocence_proof_handler.go
> +		}
This error shouldn't happen because we are escalating expired accusations, therefore messages should be for old height, for which we can get the committee

2024-07-26 14:38 UTC, lorenzo-dev1 commented on autonity/tests/accusations_test.go
> +	r.evm.Context.GetHash = func(n uint64) common.Hash { return common.Hash{0xca, 0xfe} }
I think you shouldn't return `common.Hash{0xca, 0xfe}` here because otherwise is going to affect the tests in a wrong way. These tests should be testing the accusation timing, without the check on block commit interferring. I think it would be better to return `common.Hash{}`

2024-07-26 14:40 UTC, lorenzo-dev1 commented on autonity/tests/accusations_test.go
>  	})
I think this test is duplicated with the first one

2024-07-26 14:50 UTC, lorenzo-dev1 commented on e2e_test/byzantine/collusion/helpers.go
> +	committee := c.Backend().BlockChain().Genesis().Header().Committee()
Not sure if this can be an issue, but maybe it is better to take the committee from the last epoch header instead of genesis. So that if a committee change happens, we fetch the right one.

2024-08-13 09:13 UTC, Jason-Zhangxin-Chen commented on Makefile
> -test-contracts-truffle-fast: contracts test-contracts-pre start-ganache
> I am fine with removing the `fast` truffle tests from the CI as they get run against autonity anyways, but I think it is still useful to keep this Makefile target to run the test locally in a fast way.

As CI now runs the contract tests concurrently, it is much faster than the fast test. However it is valid to run fast tests locally in a fast way. I will keep it.

2024-08-13 09:26 UTC, Jason-Zhangxin-Chen commented on core/types/autonity_header_methods.go
> -}
> Not a big deal but since we have a small function left `isGenesis`, might as well be worth to move it to block.go and remove this file

Refine this via fd216d8671098bdb2c3839bf55d39ba5798a976d

2024-08-13 10:35 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
> +        }
> I think we can assign the `blockEpochMap` value for genesis at `finalizaInitialization` and avoid this edge case check here

Refined it with 21c7fa09f57c012219d83365e44af897da7ef865

2024-08-13 10:35 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
> +        }
> I think it would be better to have a more explicit check on the epoch id (like checking whether `eID` is equal to the current epoch id)

Refined it with 21c7fa09f57c012219d83365e44af897da7ef865

2024-08-13 10:40 UTC, Jason-Zhangxin-Chen commented on autonity/autonity_test.go
> -
> Are these tests moved somewhere?
> 
> Moreover as far as I understand we now have two ways of computing the proposer, one on-chain and one off-chain. Is that right?
> 
> If yes, I think we should have tests that make sure that both computations give the same result.

We have two ways for proposer election with the same algorithm, thus it relys on the committee state saves at the state DB. I will add such kind of test to make sure the two ends elects the same proposer.

2024-08-13 11:03 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/test/utils.js
> +    autonityConfig.protocol.epochPeriod = firstEpochEndBlock;
> Is this epoch period logic still needed now that we have in finalize: `bool epochEnded = lastEpochBlock + config.protocol.epochPeriod <= block.number;`
> 
> With the `<=` it should finalize the epoch even if we have exceeded the epoch period

It is needed on purpose with the supporting of `bool epochEnded = lastEpochBlock + config.protocol.epochPeriod <= block.number;`  which makes the epoch finalisable and sets the proposer epoch period in the testing context.

2024-08-13 11:03 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/test/utils.js
>      const autonityTest = await createAutonityTestContract(validators, autonityConfig, {from: deployer});
> same here

same as my last response.

2024-08-13 11:11 UTC, Jason-Zhangxin-Chen commented on core/blockchain.go
> +		bc.epochHeadFeed.Send(newBlock.Header())
> Is it intended that we are sending the header without wrapping it into a `EpochHeadEvent` as we do in `writeBlockAndSetHead` ?

This is a bug, I fix it in 17f1ccc3c1e0d7d369c4989272f930675ede9b68. Thank you Lorenzo.

2024-08-13 12:22 UTC, Jason-Zhangxin-Chen commented on core/rawdb/chain_iterator.go
> +	// todo: double check if we need to set the epoch header.
> What happens if we do not have the marker of the epoch block? does the node crash?

No, it shouldn't happen. The initialization of header chain always load the genesis block's header as the latest epoch header by default, it is updated if there were available epoch header marker from db as each epoch header's hash is marked on the runtime in DB. The start up of the blockchain reset the chain to genesis block if the db is corrupted. With the marked epoch head hash, we can always get the corresponding block header from blockchain DB or from the freezer DB.

2024-08-13 12:34 UTC, Jason-Zhangxin-Chen commented on core/genesis.go
> +	}
> redundant

removed in 0a510a5b9c128c3648bfc6d6ec10dde6a7bf8180

2024-08-13 12:48 UTC, Jason-Zhangxin-Chen commented on core/types/bft.go
> +	h.Epoch = *epoch
> Maybe we can add a check that epoch is not nil

resolved in d4d22dd3ba25f0d879a7e75f6dba041ebaa85100

2024-08-13 12:48 UTC, Jason-Zhangxin-Chen commented on core/blockchain_reader.go
> +				bc.log.Warn("cannot find parent epoch header, trying to get committee from state DB", "epoch block", parentEHead)
> resolved in d4d22dd3ba25f0d879a7e75f6dba041ebaa85100

2024-08-13 12:48 UTC, Jason-Zhangxin-Chen commented on core/blockchain_reader.go
> +		panic("missing epoch head, chain DB might corrupted.")
> Would be good to add also the `err` to the panic message, for easier debugging if this scenario happens

resolved in d4d22dd3ba25f0d879a7e75f6dba041ebaa85100

2024-08-13 13:18 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> +		Epoch:             h.Epoch.Copy(),
> Can we have `h.Epoch` == nil here?

No, it is a value of Epoch rather than a pointer.

2024-08-13 13:22 UTC, Jason-Zhangxin-Chen commented on core/types/gen_header_json.go
> -	}
> I think this part was deleted by mistake? We should probably stick with auto generating this file automatically to avoid this kind of mistakes

don't know how it happens, it is recovered in 264b6ed43dea794a5154895054d70517bf2b29be

2024-08-13 13:52 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +	return e.ParentEpochBlock != nil && e.NextEpochBlock != nil && e.Committee != nil && e.Committee.Len() > 0
> Can we have an epoch header with non-nil committee pointer but length == 0? It means we validated an epoch block with empty committee?

No, we cannot. In the block assemble phase, only non-nil committee and with a length of committee memeber greater than 0 will triggers an epoch header construction.

2024-08-13 14:03 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +	defer c.lock.RUnlock()
> Unless I am missing something I think we do not need the lock here

resolved in fd938c1ea52840716cb6edc80e7336903937e06c.

2024-08-13 16:11 UTC, yazzaoui commented on core/types/block.go
> +	Epoch             Epoch              `json:"epoch"               gencodec:"required"`
`Epoch` need to be a pointer here to be more space efficient.

2024-08-13 16:23 UTC, yazzaoui commented on core/types/block.go
> +	Epoch             Epoch              `json:"epoch" gencodec:"required"`
I think ideally we need to have this sort of header structure:
```go
// Header represents a block header in the Autonity blockchain.
type Header struct {
	// NOTE: HeaderParentHashFromRLP relies on ParentHash being the first element of the struct. Do not move it.
	ParentHash  common.Hash    `json:"parentHash"       gencodec:"required"`
	UncleHash   common.Hash    `json:"sha3Uncles"       gencodec:"required"`
	Coinbase    common.Address `json:"miner"            gencodec:"required"`
	Root        common.Hash    `json:"stateRoot"        gencodec:"required"`
	TxHash      common.Hash    `json:"transactionsRoot" gencodec:"required"`
	ReceiptHash common.Hash    `json:"receiptsRoot"     gencodec:"required"`
	Bloom       Bloom          `json:"logsBloom"        gencodec:"required"`
	Difficulty  *big.Int       `json:"difficulty"       gencodec:"required"`
	Number      *big.Int       `json:"number"           gencodec:"required"`
	GasLimit    uint64         `json:"gasLimit"         gencodec:"required"`
	GasUsed     uint64         `json:"gasUsed"          gencodec:"required"`
	Time        uint64         `json:"timestamp"        gencodec:"required"`
	Extra       []byte         `json:"extraData"        gencodec:"required"`
	MixDigest   common.Hash    `json:"mixHash"`
	Nonce       BlockNonce     `json:"nonce"`
	// BaseFee was added by EIP-1559 and is ignored in legacy headers.
	BaseFee *big.Int `json:"baseFeePerGas"`

	/*
		PoS header fields, round & quorumCertificate not taken into account
		for computing the sigHash.
	*/
	ProposerSeal      []byte              `json:"proposerSeal"        gencodec:"required"`
	Round             uint64              `json:"round"               gencodec:"required"`
	QuorumCertificate *AggregateSignature `json:"quorumCertificate"      gencodec:"required"`
	EpochExtra        *Epoch              `json:"epochExtra"      gencodec:"required"`
}
```
So block proposal means `QuorumCertificate == nil` and non block header means `EpochExtra != nil`

2024-08-13 16:28 UTC, yazzaoui commented on core/types/block.go
> +	Epoch             Epoch              `json:"epoch"               gencodec:"required"`
After discussion with Lorenzo I think we should remove altogether `headerExtra` and have the rlp serialization following the block header structure we defined: It doesn't bring any benefit to reencode PoS fields within Extra.

2024-08-13 16:30 UTC, yazzaoui commented on core/types/block.go
> +	return h.Epoch.ParentEpochBlock
redundant just use `h.Epoch.ParentEpochBlock`

2024-08-13 16:31 UTC, yazzaoui commented on core/types/block.go
> +	return h.Epoch.NextEpochBlock
just use `h.Epoch.NextEpochBlock`

2024-08-13 16:32 UTC, yazzaoui commented on core/types/block.go
> +	return h.Epoch.IsEpochHeader()
If Epoch object was a pointer this condition could just be `h.Epoch != nil`

2024-08-13 16:34 UTC, yazzaoui commented on core/types/bft.go
> +	newHeader.Epoch = Epoch{}
Lorenzo is correct I think this is a bug. We need the epoch elements to be included within the hash computations.

2024-08-14 07:52 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +func (c *Committee) Sort() {
> We have both `Committee.Sort` and `SortCommitteeMembers` which do the same thing so we should probably delete one

Remove one of them, now unified in this 75cc992bbb569d377c4f934528df66bff3c16331

2024-08-14 07:54 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +func (c *Committee) Proposer(height uint64, round int64) common.Address {
> I think we need some tests that check that this implementation gives the same result as the on-chain one

This test is going to be placed in the new test framework of contracts.

2024-08-14 08:17 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +func (c *Committee) Equal(other *Committee) bool {
> Would be good to have some tests for this func

Added tests for epoch.go in this commit: e9604fb4945a990d64bc4cf3fe2111454e1c1a67

2024-08-14 09:15 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/backend.go
> +		if !committee.Equal(header.Committee()) {
> Other than checking if the committee match, I think we should also check that the `parentEpochBlock` and `nextEpochBlock` match the ones provided in the proposal.

Refine the match of epoch info in 254e8d56f306b6fd8aaf4e130241bdfaf763b9d4 and 14aa5b44f3cfc7573ad470c83058c5546dabed25

2024-08-15 02:59 UTC, Jason-Zhangxin-Chen commented on autonity/calls.go
> +	committee.Members = committeeMembers
> I think maybe it would be simpler to also return `epochEnded` boolean from the autonity contract.
> 
> This way here the code would be easier to understand, moreover in the autonity contract we would have:
> 
> ```
> return (contractUpgradeReady, epochEnded, committee, parentEpochBlock, nextEpochBlock);
> ```
> 
> instead of:
> 
> ```
>         if (epochEnded) {
>             return (contractUpgradeReady, committee, parentEpochBlock, nextEpochBlock);
>         }
>         CommitteeMember[] memory emptySet;
>         return (contractUpgradeReady, emptySet, parentEpochBlock, nextEpochBlock)
> ```

Resovled in 3e8f08ca4da6526d20843ba7c49ce1c192172e9e

2024-08-15 03:06 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> +		Epoch:             h.Epoch.Copy(),
As the typing of Epoch in block header is changed to a pointer in 3e8f08ca4da6526d20843ba7c49ce1c192172e9e, now it is checked with nil.

2024-08-15 03:07 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +//go:generate gencodec -type CommitteeMember -field-override committeeMemberMarshaling -out gen_member_json.go
> I think we probably need something similar for the `Epoch` struct as well

Resovled in 3e8f08ca4da6526d20843ba7c49ce1c192172e9e by implementing the json encoder and decoder for epoch structure.

2024-08-15 03:09 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +	return e.ParentEpochBlock != nil && e.NextEpochBlock != nil && e.Committee != nil && e.Committee.Len() > 0
> > Can we have an epoch header with non-nil committee pointer but length == 0? It means we validated an epoch block with empty committee?
> 
Replace the epoch typing in block header with a pointer in 3e8f08ca4da6526d20843ba7c49ce1c192172e9e, thus this is resolved by checking if the epoch pointer is nil.

2024-08-15 03:11 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/backend.go
> +			}
> I am wondering if we really need this check. All `committee`, `parentEpochBlock` and `nextEpochBlock` are computed locally and independently from the proposal. If we end up in one of this error branches, we probably have a programming error. I don't think we can end up here even when we are dealing with an invalid proposal.

Resovled in 3e8f08ca4da6526d20843ba7c49ce1c192172e9e

2024-08-15 03:11 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/engine.go
> +	if committee != nil && committee.Len() > 0 {
> Again, I think this logic could be made easier if we would return `epochEnded` from the Autonity contract

Resovled in 3e8f08ca4da6526d20843ba7c49ce1c192172e9e

2024-08-15 03:14 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/engine.go
> +	}
> do we have guarantee that when we verify an header it always belong to the LatestEpoch we have stored on-chain?

We do, unless the db is corrupted or the headers is from a malicious peer. I add a range checker in the following header verifier to check if the header is in the corresponding range of the resolved epoch. It will reject the inserting of the new header, and logging the error. See 3e8f08ca4da6526d20843ba7c49ce1c192172e9e

2024-08-15 03:27 UTC, Jason-Zhangxin-Chen commented on core/blockchain_reader.go
> +	// always get it from LRU cache first
> I think we need an additional edge case to deal with fetching the genesis committee (height == 0)

Add a short circuit for genesis height in 9f4f1d391fdb73384a5b67a08f1fbdaf40ee4f09

2024-08-15 03:30 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/engine_test.go
> +	committee, err := chain.CommitteeOfHeight(0)
> Is this test useful? and how does it work?
> 
> I had tried to understand what it is supposed to check in the past but couldn't figure it out

I removed this test since it was used for legacy implementations which is out of updated. b7b9f1352eb7f9a8646ce9adbd752bedc062882e

2024-08-15 03:39 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/handler.go
> +		//sb.logger.Crit("Missing committee for non-future consensus message", "height", msg.H())
> I think here we should still always be able to fetch the committee? Since we are not sending future height messages here. Am I missing something?

It shouldn't happens, now I let it panic in 094b244a07f1bb9a15786839aef8b174698cde58

2024-08-15 03:44 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/committee/committee_test.go
> -}
> Committee members should still be sorted right?
> 
> I see that in `newRoundRobinSet` we still call the sort function, so I think this test should still pass?

This test is useless now as the sort of committee is done by precompile contract by comparing the voting power, thus the general sort.IsSorted() never work again.

2024-08-15 04:03 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/committee/committee_test.go
>  		}
> If we want to make the array unsorted I think we have to swap if comp > 0, unless I am missing something.
> 
> Basically if the voting power is in the expected decreasing order, then we have to swap.

I removed this part since committee is always sorted by voting power in the protocol, thus I keep it same in this test context. See 598563754fa4ec75616ee4e23520b963216848b4

2024-08-15 04:28 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/precommit.go
> +	}
> I don't think this can happen, unless the changes of this PR made this scenario possible.
> 
> if we send a precommit we should be in the committee.

It does not happen indeed. I replaced the logging with critical log in c4b955cbdc476ef019bdc1e02b978781f0793b28

2024-08-15 04:28 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/prevote.go
> +	}
> I don't think this can happen, unless the changes of this PR made this scenario possible.
> 
> if we send a prevote we should be in the committee.

It does not happen indeed. I replaced the logging with critical log in c4b955cbdc476ef019bdc1e02b978781f0793b28

2024-08-15 04:28 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/propose.go
> +	}
> I don't think this can happen, unless the changes of this PR made this scenario possible.
> 
> if we send a propose we should be in the committee.

It does not happen indeed. I replaced the logging with critical log in c4b955cbdc476ef019bdc1e02b978781f0793b28

2024-08-15 04:36 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/upon_condition_test.go
> -	h.Committee = c.Committee()
> Shouldn't we set the committee in the `Epoch` field?

The naming of this helper is no longer reflective, I would like to change it to sealProposal. See 92b20bc2b8986027305fc2e6965a81d721b3a29d, epoch could be nil in a proposal for none epoch block.

2024-08-15 04:40 UTC, Jason-Zhangxin-Chen commented on consensus/acn/committee_watcher.go
> +		acn.log.Crit("Could not retrieve latest epoch, chain db might be corrupted")
> good to add err to the log for ease of debugging

Improved logging in 498b4269607ef18227ee06fc289c1185886d1bf1

2024-08-15 04:47 UTC, Jason-Zhangxin-Chen commented on eth/backend.go
> +		s.log.Info("starting sub modules for Tendermint BFT engine")
> Just curious, why do we need this additional switch now

Because in those legacy PoW engine test contexts, if we start those bft engine sub modules for PoW engine, it will fail the tests for PoW.

2024-08-15 05:14 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +	if hash == p.Message.Value() {
> I would still keep the check in `preVerifiyAccusation` as it was before. This is so that the offchain accusation verification does this check as well.
> 
> If too complex, an alternative solution is to add this check to the offchain accusation verification as well.

In the offchain accusation process logic, if the suspected value is committed,  the prover need to send the corresponding innocence proof to the sender. So I removed this from the off-chain accusation work flow to let this only work for on-chain accusation.

2024-08-15 05:30 UTC, Jason-Zhangxin-Chen commented on eth/backend.go
> +	updateConsensusEnodes := func(epochHeader *types.Header) {
> Regarding the argument name, I think we might call this func also with non-epoch header headers. Such as on line 628.

refine the naming in ed236fcada5eb24ea5409bcba831754a7f435496

2024-08-15 05:30 UTC, Jason-Zhangxin-Chen commented on eth/backend.go
> +		return
> Unless I am missing something, I think we should panic/crit here

refine the logging in ed236fcada5eb24ea5409bcba831754a7f435496

2024-08-15 06:06 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +	ret, _, err := evm.Call(vm.AccountRef(params.DeployerAddress), params.AutonityContractAddress, packedArgs, gas, new(big.Int))
> I am still thinking about this, but I have two doubts:
> 
> 1. is it fine to set gas to MaxUint64?
> 2. Is it fine to use the `DeployerAddress` as the caller (when actually we are executing the call from a precompiled).

Resolved the caller in deeca388985b7ea1e7c930b4c78f20984b8b7f28, however I am still thinking on how to resolve a reasonalbe gas cap for this call.

2024-08-15 06:06 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +	if len(committeeSet) != 0 {
> is it possible that `getCommitteeeByHeight` returns a zero length committee?

It is not possible, thus I make it panic and refined in deeca388985b7ea1e7c930b4c78f20984b8b7f28

2024-08-15 06:07 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +		}
> why do we need this copy? cannot we just do `committee.Members = committeeSet`?

This is not needed, I refine this part in deeca388985b7ea1e7c930b4c78f20984b8b7f28

2024-08-15 06:08 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +	return committee, err
> Here we should return `nil` as error I think

In that case, the err should be alway nil, I refine this within deeca388985b7ea1e7c930b4c78f20984b8b7f28

2024-08-15 06:57 UTC, Jason-Zhangxin-Chen commented on e2e_test/byzantine/collusion/helpers.go
> +	committee := c.Backend().BlockChain().Genesis().Header().Committee()
> Not sure if this can be an issue, but maybe it is better to take the committee from the last epoch header instead of genesis. So that if a committee change happens, we fetch the right one.

resolved in d2cf1313a43b8dd7541cef71006204036c6f318b

2024-08-15 06:57 UTC, Jason-Zhangxin-Chen commented on autonity/tests/accusations_test.go
>  	})
> I think this test is duplicated with the first one

resolved in d2cf1313a43b8dd7541cef71006204036c6f318b

2024-08-15 06:57 UTC, Jason-Zhangxin-Chen commented on autonity/tests/accusations_test.go
> +	r.evm.Context.GetHash = func(n uint64) common.Hash { return common.Hash{0xca, 0xfe} }
> I think you shouldn't return `common.Hash{0xca, 0xfe}` here because otherwise is going to affect the tests in a wrong way. These tests should be testing the accusation timing, without the check on block commit interferring. I think it would be better to return `common.Hash{}`

resolved in d2cf1313a43b8dd7541cef71006204036c6f318b

2024-08-15 06:58 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/innocence_proof_handler.go
> +		}
> This error shouldn't happen because we are escalating expired accusations, therefore messages should be for old height, for which we can get the committee

resolved in d2cf1313a43b8dd7541cef71006204036c6f318b

2024-08-15 06:58 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
>  	}
> I think this shoudln't happen since we do not send future height messages to the fault detector. I think this function should not return an error, since we should always be capable of computing the proposer of a non-future msg. Moreover right now if we return an error, the `isProposerValid` will return false and push a misbheaviour proof on-chain, which I don't think is correct.

resolved in d2cf1313a43b8dd7541cef71006204036c6f318b

2024-08-15 06:59 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +	}
> I think this should never happen as normally we do not send future height msgs to the fault detector

resolved in d2cf1313a43b8dd7541cef71006204036c6f318b

2024-08-15 06:59 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +	}
> I think this should never happen as normally we do not send future height msgs to the fault detector

resolved in d2cf1313a43b8dd7541cef71006204036c6f318b

2024-08-15 06:59 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +		return false
> Unless I am missing something, this scenario still cannot happen

resolved in d2cf1313a43b8dd7541cef71006204036c6f318b

2024-08-15 07:09 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +func (c *Committee) Proposer(height uint64, round int64) common.Address {
> > I think we need some tests that check that this implementation gives the same result as the on-chain one
> 
> The proposer election in AC contract is not use anymore, now it is unified at the committee structure.

2024-08-15 07:14 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> +	Epoch             Epoch              `json:"epoch"               gencodec:"required"`
> `Epoch` need to be a pointer here to be more space efficient.

3e8f08ca4da6526d20843ba7c49ce1c192172e9e resolved this comment.

2024-08-15 11:39 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> +		}
> I assume we need these checks on decoding of the block, maybe it would be better to move them out of `EnrichEpochInfo` and into the callers, so that we perform these checks only where we need them. Moreover it is more semantically correct that the `Enrich` method just adds data to the struct without performing validity checks

Refined in d6a026b3e35f24f509426b07ee95d58e2b039d66

2024-08-15 11:52 UTC, Jason-Zhangxin-Chen commented on core/headerchain.go
> +		// todo: (Jason) check if this reorg context happens for instant BFT consensus? Or is it possible for fork?
> I think we should solve this one before merging to develop, it is important

The reorg should not happen to BFT instant consensus protocol, I add a few code comments via 68f057507b6e268830e074d807ab0cf4cec2a560

2024-08-15 12:17 UTC, Jason-Zhangxin-Chen commented on consensus/acn/committee_watcher.go
> +		updateConsensusEnodes(currentHead)
> I am wondering if `LastEpoch` and `CurrentHeader` should be executed "atomically". I am thinking about the case where we are at the edge of an epoch and `LastEpoch` still returns the information about the past epoch, while `CurrentHeader` already returns a block from the new epoch. Not sure if this is possible though, need to think about it more.

Resolved in 26ca0d78687e4c1494ecbde270cac82eeb43fdff, now we fetch the committee base on the current chain's head state.

2024-08-15 12:18 UTC, Jason-Zhangxin-Chen commented on eth/backend.go
> +	if committee.MemberByAddress(s.address) != nil {
> I am wondering if `LastEpoch` and `CurrentHeader` should be executed "atomically". I am thinking about the case where we are at the edge of an epoch and `LastEpoch` still returns the information about the past epoch, while `CurrentHeader` already returns a block from the new epoch. Not sure if this is possible though, need to think about it more.

Resolved in 26ca0d78687e4c1494ecbde270cac82eeb43fdff, now we fetch the committee base on the current chain's head state on the start up of committee watchers.

2024-08-15 12:35 UTC, Jason-Zhangxin-Chen commented on core/types/bft.go
> +	newHeader.Epoch = Epoch{}
I see, don't know how this line was removed. I thought that the extra field was included in the hash computing. I will remove this extra field as what you proposed for the block header. Now we don't need this extra field for those PoS filtered fields.

2024-08-15 13:10 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> +	Epoch             Epoch              `json:"epoch" gencodec:"required"`
Resolved in 

> I think ideally we need to have this sort of header structure:
> 
> ```go
> // Header represents a block header in the Autonity blockchain.
> type Header struct {
> 	// NOTE: HeaderParentHashFromRLP relies on ParentHash being the first element of the struct. Do not move it.
> 	ParentHash  common.Hash    `json:"parentHash"       gencodec:"required"`
> 	UncleHash   common.Hash    `json:"sha3Uncles"       gencodec:"required"`
> 	Coinbase    common.Address `json:"miner"            gencodec:"required"`
> 	Root        common.Hash    `json:"stateRoot"        gencodec:"required"`
> 	TxHash      common.Hash    `json:"transactionsRoot" gencodec:"required"`
> 	ReceiptHash common.Hash    `json:"receiptsRoot"     gencodec:"required"`
> 	Bloom       Bloom          `json:"logsBloom"        gencodec:"required"`
> 	Difficulty  *big.Int       `json:"difficulty"       gencodec:"required"`
> 	Number      *big.Int       `json:"number"           gencodec:"required"`
> 	GasLimit    uint64         `json:"gasLimit"         gencodec:"required"`
> 	GasUsed     uint64         `json:"gasUsed"          gencodec:"required"`
> 	Time        uint64         `json:"timestamp"        gencodec:"required"`
> 	Extra       []byte         `json:"extraData"        gencodec:"required"`
> 	MixDigest   common.Hash    `json:"mixHash"`
> 	Nonce       BlockNonce     `json:"nonce"`
> 	// BaseFee was added by EIP-1559 and is ignored in legacy headers.
> 	BaseFee *big.Int `json:"baseFeePerGas"`
> 
> 	/*
> 		PoS header fields, round & quorumCertificate not taken into account
> 		for computing the sigHash.
> 	*/
> 	ProposerSeal      []byte              `json:"proposerSeal"        gencodec:"required"`
> 	Round             uint64              `json:"round"               gencodec:"required"`
> 	QuorumCertificate *AggregateSignature `json:"quorumCertificate"      gencodec:"required"`
> 	EpochExtra        *Epoch              `json:"epochExtra"      gencodec:"required"`
> }
> ```
> 
> So block proposal means `QuorumCertificate == nil` and non block header means `EpochExtra != nil`

As the typing of Epoch in block header is changed to a pointer in 3e8f08ca4da6526d20843ba7c49ce1c192172e9e, now it is checked with nil.

2024-08-15 13:12 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> +	return h.Epoch.ParentEpochBlock
> redundant just use `h.Epoch.ParentEpochBlock`

resolved in d601f92a18c5b988c9dbb4511ead74c1b5e73ef5

2024-08-15 13:12 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> +	return h.Epoch.NextEpochBlock
> just use `h.Epoch.NextEpochBlock`

resolved in d601f92a18c5b988c9dbb4511ead74c1b5e73ef5

2024-08-15 13:14 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> +	return h.Epoch.IsEpochHeader()
> If Epoch object was a pointer this condition could just be `h.Epoch != nil`

resolved in b9d414563bb2eae711f88a0fe416a26ed153156e

2024-08-15 13:16 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> +	Epoch             Epoch              `json:"epoch"               gencodec:"required"`
> After discussion with Lorenzo I think we should remove altogether `headerExtra` and have the rlp serialization following the block header structure we defined: It doesn't bring any benefit to reencode PoS fields within Extra.

regarding the removal of header's Extra field, since this is a standard field of the ETH application field, and a lots of other components still use it, if we really want to remove it, than it would greate to create another PR for it as current PR is a big one already.

2024-08-20 08:21 UTC, lorenzo-dev1 commented on autonity/solidity/test/utils.js
> +    autonityConfig.protocol.epochPeriod = firstEpochEndBlock;
Yeah but the epoch would finalize even if we are at a `block.number >= lastEpochBlock + config.protocol.epochPeriod`, so why do we need to lengthen the epoch period?

Basically I think that the comment statement: `As the chain height might exceed the lastEpochBlock(0)+EpochPeriod(30) of the newly deployed AC with a lots of blocks, it makes the AC impossible to finalize an epoch,` is not true anymore. Thus we shouldn't need this logic to finalize the epoch I think.

Or does this cause any other issue?

2024-08-20 08:33 UTC, lorenzo-dev1 commented on core/rawdb/chain_iterator.go
> +	// todo: double check if we need to set the epoch header.
Ok so even if we init the db from freezer, it will set the epoch block marker right?

2024-08-21 09:35 UTC, Jason-Zhangxin-Chen commented on core/rawdb/chain_iterator.go
> +	// todo: double check if we need to set the epoch header.
> Ok so even if we init the db from freezer, it will set the epoch block marker right?

Yes, Epoch block marker (contains the hash to the block number) is not moved to freezer DB, it always stay at the level DB side. This InitDatabaseFromFreezer function rebuild the `hash` to `block number` mapping for the blockchain DB (level db) for ancient blocks which were removed from level DB when migrate to freezer DB. Thus, we always have the right epoch block marker. With the hash -> number mapping, the blockchain can get block/header either from level DB or from the freezer DB if the target is not found from level DB.

2024-08-21 10:34 UTC, lorenzo-dev1 reviewed
Some more comments on the new changes

2024-08-21 14:31 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
> +        // otherwise returns finalized history epoch's committee
> I think there is at bug here in case that `_height == block.number` and `block.number` has not been finalized yet.
> 
> In that case the `blockEpochMap` value will not be set (as finalize didn't execute yet for the current block) and therefore we will return the genesis committee instead of the current one.
> 
> I think that's what will happen but maybe it is worth to verify with a test.
> 
> Is this something that can happen?

In most of the case, the block should be already finalized, but I think this assumption shall introduce bugs. I think the best implementation as what I did at here: 1bacd2671a50e21c776a06fc59c72d758deb7d8a. Thank you Lorenzo for this finding.

2024-08-21 14:32 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
>  	return proposer, nil
> The returned error is always nil so I think we can remove it

refined in this 1bacd2671a50e21c776a06fc59c72d758deb7d8a

2024-08-22 09:47 UTC, Jason-Zhangxin-Chen commented on eth/backend.go
> +		s.log.Info("starting sub modules for Tendermint BFT engine")
This becomes a problem from with epoch header, as the committee info cannot be get from parent block's header, now the sub-components (committee wather, validator controller, etc...) of tendermint consensus engine need to fetch committee from AC contracts which is not deployed for POW consensus engine. In this case, to make the legacy tests for PoW engines work, we only starts these sub components for tendermint.

2024-08-22 09:47 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> -	Epoch             Epoch              `json:"epoch"               gencodec:"required"`
> I think we need the rlp:nil tag but also the json one

We do have one in my recent refine of the epoch typing with pointer.

2024-08-22 10:07 UTC, Jason-Zhangxin-Chen commented on core/vm/contracts.go
> +	validators := make([]types.CommitteeMember, 0, validatorListSize)
> Just curious, why changing from array of pointers to array of values?

It is because the unified sorting function of committee takes array of values to sort.

2024-08-22 10:27 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +	}
> I think we need the nil check on `e.Committee`?

See the tests TestCommittee_Equal, it does not panic.

2024-08-22 10:28 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +	slices.SortStableFunc(members, func(a, b CommitteeMember) int {
> just curious, why change to non-pointers

To unified them into one sorting method called by contracts and the other components.

2024-08-22 11:16 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +
> That's weird, I do not understand why we need that.

I will remove this. It was due to the difference of the presenting of big.Int(0). The `abs` field of type `nat` of big.Int(0) parsed by the JSON lib contains a word array with 0 item of 1 length, however in the common.Big0, the corresponding field is a nil pointer. That is why the deep.Equal fails in the block_test.go. Normally we should use big.Int.Cmp() to compare the big.Ints fields in the block, however it will be a huge work to do so. Thus I keep the deep equal there, and replace the common.Big0 with common.Big1.

2024-08-22 12:40 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/committee/committee_test.go
> -}
We should already have one, I will check with @tbssajal, do we have a test to cover if the committee sorting from the precomile contract works? Otherwise I will add one.

2024-08-22 12:40 UTC, Jason-Zhangxin-Chen commented on core/types/bft_test.go
> +			posHeaderHash,
I got it, I think there is a bug in this tests, will need to fix it.

2024-08-22 12:40 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +	if hash == p.Message.Value() {
Resolved it in 781584772a11dc7f7678753643b07f2312bded80, as the chain context is removed from the precompile contract side, thus accusation handler does not share the same chain context interface, now I put this checker right after the preValidateAccusation.

2024-08-22 12:40 UTC, Jason-Zhangxin-Chen commented on autonity/tests/accusations_test.go
> -		_, err := r.accountability.HandleEvent(&runOptions{origin: reporter}, NewAccusationEvent(accusationHeight, common.Hash{0xca, 0xfe}))
It is recoverd in 781584772a11dc7f7678753643b07f2312bded80

2024-08-22 12:40 UTC, Jason-Zhangxin-Chen commented on autonity/tests/accusations_test.go
> +	r.evm.Context.GetHash = func(n uint64) common.Hash { return common.Hash{0xca, 0xfe} }
resolved in 781584772a11dc7f7678753643b07f2312bded80

2024-08-22 12:40 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/precommit.go
> +		c.logger.Crit("validator is no longer in current committee")
> Would be good to print also the error content here and in prevote.go and propose.go

resolved in 781584772a11dc7f7678753643b07f2312bded80

2024-08-22 12:44 UTC, Jason-Zhangxin-Chen commented on consensus/acn/committee_watcher.go
> +		updateConsensusEnodes(currentHead)
Indeed, I fix this one in 781584772a11dc7f7678753643b07f2312bded80. However we need to review current repo to avoid this. So far I fix some other cases which is similar like this in this commit 781584772a11dc7f7678753643b07f2312bded80, need to double check if we still have such cases.

2024-08-22 12:44 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> +	return h.Epoch.Committee.Enrich()
> At this point I think that we can directly call the enrich on the committee and don't need this wrapper method

resolved it in 781584772a11dc7f7678753643b07f2312bded80.

2024-08-22 12:44 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
>  		}
> I think we can reject at decoding also an epoch block with committee of length 0

Add it in 781584772a11dc7f7678753643b07f2312bded80

2024-08-22 12:45 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +
> > That's weird, I do not understand why we need that.
> 
> I will remove this. It was due to the difference of the presenting of big.Int(0). The `abs` field of type `nat` of big.Int(0) parsed by the JSON lib contains a word array with 0 item of 1 length, however in the common.Big0, the corresponding field is a nil pointer. That is why the deep.Equal fails in the block_test.go. Normally we should use big.Int.Cmp() to compare the big.Ints fields in the block, however it will be a huge work to do so. Thus I keep the deep equal there, and replace the common.Big0 with common.Big1.

resolved it in 781584772a11dc7f7678753643b07f2312bded80

2024-08-22 12:45 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +		cpy.ParentEpochBlock = new(big.Int).SetUint64(e.ParentEpochBlock.Uint64())
> For copying big.Int we can use `Set` and avoid converting to uint64 which can cause data loss

resolved in 781584772a11dc7f7678753643b07f2312bded80

2024-08-22 12:51 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/engine.go
> -			return errInvalidEpochBoundary
> I think this bidirection check is still useful here, since we are not verifying the full block

resolved in 781584772a11dc7f7678753643b07f2312bded80

2024-08-22 12:51 UTC, Jason-Zhangxin-Chen commented on core/types/bft_test.go
> +			posHeaderHash,
> I think that adding the proposerSeal to the header should make the hash different friom `posHeaderHash`, since when we hash we do not zero it out.

This is a bug in the tests, I will fix it soon.

2024-08-27 12:41 UTC, lorenzo-dev1 commented on core/types/bft_test.go
> +		if i != 6 {
commit mistake?

2024-08-27 12:41 UTC, lorenzo-dev1 commented on core/types/bft_test.go
> +		}
Commit mistake?

2024-08-27 12:45 UTC, lorenzo-dev1 commented on core/types/block.go
> +
I think we should also check that `h.Epoch.Committee != nil` to avoid a possible nil pointer dereference in decoding func

2024-08-27 12:46 UTC, lorenzo-dev1 commented on core/types/block.go
> +
And we should do it before even calling Enrich

2024-08-27 12:51 UTC, lorenzo-dev1 commented on consensus/tendermint/backend/engine.go
> +	// epoch info integrity check, this is checked at both the proposal verification and block sync phases.
The bidirection check is actually not done a proposal verification, the comment is not correct. But the code is correct

2024-08-27 13:31 UTC, Jason-Zhangxin-Chen commented on core/types/bft_test.go
> +		}
> Commit mistake?

Yeah, recovered with e34e0c19281bfed947a66ed71017b77cea763e58

2024-08-27 13:31 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
> +
Added in e34e0c19281bfed947a66ed71017b77cea763e58

2024-08-27 13:34 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/engine.go
> +	// epoch info integrity check, this is checked at both the proposal verification and block sync phases.
> The bidirection check is actually not done a proposal verification, the comment is not correct. But the code is correct

As this verifyHeader is called by VerifyHeader which be called by HandleProposal and the header verification of BlockSync. I mean the epoch integrity is checked. I made the comment updated in e34e0c19281bfed947a66ed71017b77cea763e58

2024-08-27 13:44 UTC, lorenzo-dev1 approved these changes
LGTM!

2024-08-27 14:00 UTC, Jason-Zhangxin-Chen commented
> LGTM!

Great! Thanks a lot for your findings, Lorenzo!

2024-08-29 14:27 UTC, yazzaoui commented on core/types/block.go
>  	return b.header.SanityCheck()
Can we add some checks in the SanityCheck method to verify that:
- LastEpochBlock and NextEpochBlock are uint64
- LastEpochBlock is less than current block number 
- NextEpochBlock is greater than current block number

2024-08-29 14:31 UTC, yazzaoui commented on core/types/epoch.go
> +	ParentEpochBlock *big.Int   `rlp:"nil" json:"parentEpochBlock" gencodec:"required"`
Minor change: Can we rename it to `PreviousEpochBlock`

2024-08-29 14:37 UTC, yazzaoui commented on core/types/epoch.go
> +	if (e.ParentEpochBlock == nil) != (other.ParentEpochBlock == nil) ||
The ParentEpochBlock nil and NextEpochBlock nil checks seems redundant as the deserialization mechanism will take care of ensuring those are not nils. So perhaps we can remove them to make the core more readable.

2024-08-30 12:24 UTC, Jason-Zhangxin-Chen commented on core/types/block.go
>  	return b.header.SanityCheck()
I agree with it. Thank you.

2024-08-30 14:38 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +	ParentEpochBlock *big.Int   `rlp:"nil" json:"parentEpochBlock" gencodec:"required"`
> Minor change: Can we rename it to `PreviousEpochBlock`

Resloved in 59e50b58159d183e181f3732be7f05a33f33cdd8

2024-08-30 14:38 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +	if (e.ParentEpochBlock == nil) != (other.ParentEpochBlock == nil) ||
> The ParentEpochBlock nil and NextEpochBlock nil checks seems redundant as the deserialization mechanism will take care of ensuring those are not nils. So perhaps we can remove them to make the code more readable.

Resloved in 59e50b58159d183e181f3732be7f05a33f33cdd8

2024-09-05 11:43 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
> +    uint256 public previousEpochBlock;
> previousEpochBlock seems to do same thing as LastEpochBlock. This can be removed

No, the last epoch block stand for the latest epoch block, however the previous epoch block is the one that before the latest one.

2024-09-05 11:50 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
> +        // the new epoch period will be activated until current epoch ends.
> It seems like after this change, getEpochPeriod will still return the oldEpochPeriod, Is that desirable? That could be confusing someone who is setting the epochPeriod and verifying the same. Should the Get return the newEpochPeriod

The newEpochPeriod save the new period that is going to be applied at the end of current epoch, in this case we delayed the activiation of new epoch parameter.

2024-09-05 12:02 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
> +    uint256 public lastFinalizedBlock;
> Do we need to maintain lastFinalizedBlock, Isn't it always block.number-1 (except genesis block, height==0)

In the TXN message EVM execution context of height `h`, there is two different scenarios: 1. block `h` haven't being finalized; 2. block `h` is already finalized. It will have different result of committee on this two scenario. Thus we introduce this to make sure that the block `h` is already finalized or not to have a deterministic result of committee query.

2024-09-06 03:15 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
> +        // the new epoch period will be activated until current epoch ends.
Improve it with: 78507716f806738ac47bcc69b6b7b300dc6a568d. Now if we have a new period to be applied, it will be returned, otherwise we returned the current applied one.

2024-09-06 03:16 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
>          emit EpochPeriodUpdated(_period);
Sure thing, I improved it with 78507716f806738ac47bcc69b6b7b300dc6a568d, we return the `toBeAppliedAtBlock` to the client.

2024-09-06 07:19 UTC, vpiyush commented on autonity/solidity/contracts/Autonity.sol
> +    uint256 public previousEpochBlock;
This comment is ir-relevant if fix [this](https://github.com/autonity/autonity/pull/1022#discussion_r1741839145)

2024-09-06 07:21 UTC, vpiyush commented on autonity/solidity/contracts/Autonity.sol
> +    uint256 public lastFinalizedBlock;
Same If we fix [this](https://github.com/autonity/autonity/pull/1022#discussion_r1741839145). It is automatically resolved

2024-09-06 10:37 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
> +    uint256 public previousEpochBlock;
I refine the epoch rotation in bd66e14f885136502890909888d9734a922dadde by removing those helper variables.

2024-09-06 10:38 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
> +    uint256 public nextEpochBlock;
The epoch rotation is refined in bd66e14f885136502890909888d9734a922dadde by removing those helper variables.

2024-09-06 10:49 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +	committee, err := committeeOfHeight(p.Message.H(), e, c.address)
Renamed in d84b9be8a6c3ae427dab649c99c9517d9e2c3c7c

2024-09-06 10:59 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +	if err != nil {
Refined in bdaf8729b0237610431221c7447caab7b7c26936, to return the error to precompile caller.

2024-09-06 11:12 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +		fd.logger.Crit("cannot find committee for height", "err", err, "height", m.H())
It is okay to panic for call trace.  As the AFD rule runs with delta blocks later to address faulty nodes, and the aggregator layer also filter and buffer future messages, in this case, under some scenario,  it is impossible fail to fetch committee for those known height. Thus, we want to panic only for such conditions.

2024-09-06 11:15 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +		fd.logger.Crit("cannot find committee for height", "err", err, "height", m.H())
Refined in 56dbd1edc86df506c0f15f642e226643fd885562

2024-09-06 11:47 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/aggregator.go
> +		a.logger.Crit("cannot find epoch head for height", "height", msg.H(), "err", err)
It is okay, I will replace them with panic.

2024-09-06 12:05 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/engine.go
> +		if epoch.PreviousEpochBlock == nil || epoch.NextEpochBlock == nil || epoch.Committee == nil ||
Those nil checkers were removed as they are duplicated, however I keep the boundary checker here which is not.

2024-09-06 12:09 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/engine.go
> +func (sb *Backend) verifyHeaderAgainstLastView(header, parent *types.Header, committee *types.Committee) error {
Because it not only check thing against parent block but also last epoch info. Thus I think change it with last view would make more sense.

2024-09-06 12:28 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +func (c *Committee) Enrich() error {
I don't want to introduce locks for this one for better performance. It is okay for now since on those usage of Copy(), all the corresponding of header was already cached which means the enrich() was already called once.

2024-09-06 12:34 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/committee/committee.go
> +	return &set.committee.Members[nextProposerIndex(set.roundRobinOffset, round, int64(set.committee.Len()))]
As this RoundRobinCommittee is used only for unit testing which does not have the concurrent execution context, thus I think it is okay for now, or we can create another issue to improve this?

2024-09-06 12:46 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/committee/committee.go
> +func getMemberIndex(committee *types.Committee, memberAddr common.Address) int64 {
As this RoundRobinCommittee things are used only for unit testing, I think it is okay for now, I can create issue to improve this test.

2024-09-06 12:50 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/core.go
> +		// on epoch rotation, update committee.
That is required still for proposer election, we cannot remove it for now.

2024-09-06 14:04 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/innocence_proof_handler.go
> +	if err != nil {
Resolved in 58d6e61c4740d0b5d2a8c098e896bbb1d11d8579

2024-09-06 14:04 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/innocence_proof_handler.go
> +	memberShip := committee.MemberByAddress(sender)
Resolved in 58d6e61c4740d0b5d2a8c098e896bbb1d11d8579

2024-09-06 14:04 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/innocence_proof_handler.go
> +			fd.logger.Crit("escalateExpiredAccusations", "cannot find committee", "height", accusation.Message.H(), "err", err)
Resolved in 58d6e61c4740d0b5d2a8c098e896bbb1d11d8579

2024-09-06 14:05 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/api.go
> +	return api.tendermint.GetCommitteeByHeight(new(big.Int).SetUint64(uint64(*number)))
Resolved in 58d6e61c4740d0b5d2a8c098e896bbb1d11d8579

2024-09-06 14:05 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/backend.go
> +		if epoch.PreviousEpochBlock == nil || epoch.NextEpochBlock == nil || epoch.Committee == nil ||
Resolved in 58d6e61c4740d0b5d2a8c098e896bbb1d11d8579

2024-09-06 14:05 UTC, Jason-Zhangxin-Chen commented on core/blockchain_reader.go
> +	currentBLock := bc.CurrentBlock()
Resolved in 58d6e61c4740d0b5d2a8c098e896bbb1d11d8579

2024-09-06 14:07 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/mock_engine_modify_validator_list.go
> +	// todo:(Jason) fix it
Resolved in 58d6e61c4740d0b5d2a8c098e896bbb1d11d8579

2024-09-06 14:13 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/engine.go
> +	sb.contractsMu.Lock()
It was a legacy mutex to protect the contract() object, I will try to remove it if there is no race condition can be addressed.

2024-09-06 14:13 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/mock_engine_modify_validator_list.go
> +	//todo: jason fix it.
Resolved in https://github.com/autonity/autonity/commit/58d6e61c4740d0b5d2a8c098e896bbb1d11d8579

2024-09-06 14:17 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/committee/committee.go
> +	return set.committee
Let's create an issue to improve this, it is all about the RoundRobinCommittee things which is used for unit testing.

2024-09-06 14:18 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/committee/committee.go
> +func (set *RoundRobinCommittee) GetByAddress(addr common.Address) (*types.CommitteeMember, error) {
Resolved in https://github.com/autonity/autonity/commit/58d6e61c4740d0b5d2a8c098e896bbb1d11d8579

2024-09-06 14:18 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/committee/committee.go
> +func (set *RoundRobinCommittee) GetByIndex(i int) (*types.CommitteeMember, error) {
Resolved in https://github.com/autonity/autonity/commit/58d6e61c4740d0b5d2a8c098e896bbb1d11d8579

2024-09-06 14:20 UTC, Jason-Zhangxin-Chen commented on core/headerchain.go
> +func (hc *HeaderChain) CurrentHeadEpochHeader() *types.Header {
Resolved in https://github.com/autonity/autonity/commit/58d6e61c4740d0b5d2a8c098e896bbb1d11d8579

2024-09-10 06:58 UTC, tbssajal commented on consensus/tendermint/backend/handler.go
> +	committee, err := sb.BlockChain().CommitteeOfHeight(msg.H())
Is it possible for message from old height to come here? If yes then we should use `msg.H()-1` to get committee I think, otherwise the committee would be wrong, right?

2024-09-10 10:38 UTC, tbssajal commented on core/types/epoch.go
> +	c.lock.Lock()
If there are concurrent access in this function, then I guess it is better to first add `RLock()` to just read the map. Then if the map is nil, acquire `Lock()` and fill the map. Because the map will be filled only once, this approach could be faster for concurrent access after the map is filled.

2024-09-10 10:38 UTC, tbssajal commented on core/types/epoch.go
> +	c.lock.Lock()
Same as above, we can acquire a read lock first, read, and then if it is empty acquire a write lock.

2024-09-10 10:38 UTC, tbssajal commented on consensus/tendermint/backend/handler.go
> +	committee, err := sb.BlockChain().CommitteeOfHeight(msg.H())
Never mind. I figured the header at height `msg.H()-1` has the committee for height `msg.H()`.

2024-09-10 13:14 UTC, tbssajal requested changes

2024-09-10 13:16 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
>      function getEpochPeriod() external view virtual returns (uint256) {
Now it looks like: 
```solidity
    function getEpochPeriod() external view virtual returns (uint256) {
        // if the new epoch period haven't being applied yet, return it anyway.
        if (config.protocol.epochPeriod != epochPeriodToBeApplied) {
            return epochPeriodToBeApplied;
        }
        // otherwise we return the current applied epoch period.
        return config.protocol.epochPeriod;
    }
```

2024-09-10 13:29 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
>      function getEpochPeriod() external view virtual returns (uint256) {
Both functions are doing the same thing basically. So you can leave it as it is if you wish.

2024-09-10 13:37 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/handler.go
> +	committee, err := sb.BlockChain().CommitteeOfHeight(msg.H())
No worries, old height messages does not go to here as it will be filter by the aggregator.

2024-09-10 13:40 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/backend/engine.go
> +	committee, _, cureEpochHead, nextEpochHead, err := chain.LatestEpoch()
Resolved in 7b6d66792504b916ba88da72856bdd48b6933cd1

2024-09-10 13:41 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +			clone.membersMap[k] = v
Resolved in 7b6d66792504b916ba88da72856bdd48b6933cd1

2024-09-10 13:41 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +	c.lock.Lock()
Resolved in 7b6d66792504b916ba88da72856bdd48b6933cd1

2024-09-10 13:41 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +	c.lock.Lock()
Resolved in 7b6d66792504b916ba88da72856bdd48b6933cd1

2024-09-10 14:27 UTC, tbssajal commented on core/types/epoch.go
> +			var member CommitteeMember
You could just loop through `clone.Members`, then there was no need to copy and create additional memories. But if it is not too much memory consumption, then it is fine I guess.

2024-09-11 10:38 UTC, Jason-Zhangxin-Chen commented on core/headerchain.go
> +			rawdb.WriteEpochHeaderHash(batch, hash)
Resolved in 640407fa631157c86551f4882aa6f3deaddc4e6d

2024-09-11 10:38 UTC, Jason-Zhangxin-Chen commented on core/rawdb/database.go
> +				databaseVersionKey, headHeaderKey, headEpochHeaderKey, headBlockKey, headFastBlockKey, lastPivotKey,
Resolved in 640407fa631157c86551f4882aa6f3deaddc4e6d

2024-09-11 10:39 UTC, Jason-Zhangxin-Chen commented on core/types/epoch.go
> +			var member CommitteeMember
Resolved in 640407fa631157c86551f4882aa6f3deaddc4e6d

2024-09-11 10:50 UTC, tbssajal approved these changes
LGTM!

2024-09-12 08:00 UTC, vpiyush approved these changes

2024-09-17 03:48 UTC, yazzaoui approved these changes
LGTM, let's get it merged

2024-09-17 06:39 UTC, merged

2024-09-17 06:40 UTC, Jason-Zhangxin-Chen commented
Thank you all for your contributions for this big feature.