Oracle accountability
autonity/autonity pull request #1067
Opened 2024-11-14 01:21 UTC by yazzaoui

Implement oracle accountability

WIP:
- Autobonding integration
- Tests missing

2024-11-14 09:47 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Oracle.sol
>          }
I think that the `_price` does not get updated in case that `_count` > 0. I guess it should be the median of the filtered reports?

2024-11-14 09:58 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Oracle.sol
> +        _totalOutliers = voters.length - _totalReports;
I think it would be better to keep it simple and increase the `_totalOutliers` return variable, it is already declared as a part of the return parameters anyways

2024-11-14 13:22 UTC, tbssajal requested changes

2024-11-14 13:22 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> -            _atn -= _atnProposerRewards;
Removing this enforces some additional constraints on `config.policy.proposerRewardRate` and `config.policy.oracleRewardRat`. What we need now is the following:
```
config.policy.oracleRewardRat / ORACLE_REWARD_RATE_PRECISION + config.policy.proposerRewardRat / PROPOSER_REWARD_RATE_PRECISION <= 1
```

If we consider `PROPOSER_REWARD_RATE_PRECISION = ORACLE_REWARD_RATE_PRECISION`, then we have the condition
```
config.policy.oracleRewardRat + config.policy.proposerRewardRat <= REWARD_RATE_PRECISION
```

Otherwise when doing the following
```
_atn -= _atnProposerRewards + _atnOracleRewards
```
we can get overflow error.

2024-11-14 13:22 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +        config.contracts.oracleContract.receiveRewards{value:_atnOracleRewards}();
`_ntnOracleRewards` is not passed. Is it intentional?

2024-11-14 13:54 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
> +            config.autonity.transfer(_voter, _ntn);
Shouldn't we transfer the rewards to treasury address?

2024-11-20 12:33 UTC, vpiyush commented on autonity/solidity/contracts/Oracle.sol
> +            // median here is assumed to be non-0.
a safety check for median != 0 could be added in the begining of the function

2024-11-20 12:33 UTC, vpiyush commented on autonity/solidity/contracts/Oracle.sol
> +                _penalize(_outliers[i], _priceMedian, reports[_symbol][_outliers[i]]);
len( _outliers) won't always be same as _totalOutliers. The way we are calculating _totalOutliers.  we could potentially invoke this with address 0 and report 0.

2024-11-21 16:35 UTC, yazzaoui commented on autonity/solidity/contracts/Oracle.sol
>          }
Yes, calling the price calculation function was missing here

2024-11-21 16:35 UTC, yazzaoui commented on autonity/solidity/contracts/Oracle.sol
> +            config.autonity.transfer(_voter, _ntn);
Depreciated with autobond integration

2024-11-21 17:44 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
> +            int256 _priceMedian = int256(uint256(_getMedian(_totalReports, _count)));
I think there is an issue, here. We never set `_price` here, so assuming that `_count > 0` we will never have a price that is non-zero. In addition, weren't we planning on including the confidence interval when calculating the price?

2024-11-21 18:03 UTC, yazzaoui commented on autonity/solidity/contracts/Oracle.sol
> +            int256 _priceMedian = int256(uint256(_getMedian(_totalReports, _count)));
Mentionned here https://github.com/autonity/autonity/pull/1067#discussion_r1852481511 that indeed the price calculation invocation was missing.

2024-11-21 23:49 UTC, yazzaoui commented on autonity/solidity/contracts/Oracle.sol
> +        if(_reports.length != symbols.length)  { // todo: why not require?
Good points, I'll remove this comment.

2024-11-21 23:59 UTC, yazzaoui commented on autonity/solidity/contracts/Autonity.sol
> -            _atn -= _atnProposerRewards;
Agree but this constraint enforcement can be done offline as this being a governance operation

2024-11-22 08:11 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> -            _atn -= _atnProposerRewards;
In that case we should add some checks in Prepare() function that checks the genesis config. And we should have `@notice` that explain the enforcement in both `setOracleRewardRate` and `setProposerRewardRate` function.

2024-11-25 12:23 UTC, tbssajal requested changes

2024-11-25 12:23 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
> +            if (!voterInfo[_voter].reportAvailable) {
Here the voter who did not vote will not be considered an outlier and will not be penalized. If voting is mendatory, then this voter should be an outlier or at least be penalized. Or maybe we could consider his last reported price for this symbol to determine if the voter is an outlier or not.

2024-11-25 13:43 UTC, vpiyush commented on autonity/solidity/contracts/Oracle.sol
> +            require(
if a voter calculated a 0 price and sent a commit for it in round r in the round r+1 it can not register a commit for the price report which it is going to send in r+2. because r+1 will always revert.

2024-11-27 14:19 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
> +                rewardReceivers.add(_voter);
#1085 contains a test for this which is currently failing. After the fix the test should pass.

2024-11-27 16:39 UTC, vpiyush commented on autonity/solidity/contracts/Oracle.sol
> +                _penalize(_outliers[i], _priceMedian, reports[_symbol][_outliers[i]]);
This got fixed [here](https://github.com/autonity/autonity/pull/1067/commits/ddede31011b01c9b27adea04ed1d4786b35b77a1), Resolving this comment now.

2024-11-27 17:14 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
> +        if (_diffRatio < config.outlierSlashingThreshold) {
Consider writing `if (_diffRatio <= config.outlierSlashingThreshold)` instead. Otherwise we are not realling slashing when `_diffRatio == config.outlierSlashingThreshold)` but still doing some unnecessary calls.

2024-11-28 12:39 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
> +            if (!voterInfo[_voter].reportAvailable) {
In this case, the voter is omission faulty, its loss of the performance score causes the decreasing of its fractions of the ATN & NTN reward, and there is no slashing penalty for omission faulty node. 

We don't reset `reportAvailable` after a voting round, so in general we are already using the previously submitted price in the case that a user does not submit a new price. The only scenario where `reportAvailable` will be false is if a voter has never submitted a report, or the voter set just changed (ie. epoch end).

2024-11-28 12:45 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
> +            if (!voterInfo[_voter].reportAvailable) {
I see. But in that case someone who never submits a vote will be in profit compared to an outlier, right? Because the outlier is getting slashed and not getting any rewards?

2024-11-28 12:51 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
> +        if (_diffRatio < config.outlierSlashingThreshold) {
Fair point, done.

2024-11-28 12:52 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
> +            if (!voterInfo[_voter].reportAvailable) {
Yes, this is correct. Outlier behavior is counted as malicious, rather than just omission faulty.

2024-11-28 12:55 UTC, merged

2024-11-28 12:57 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
> +            if (!voterInfo[_voter].reportAvailable) {
Alright makes sense.

2024-11-28 12:57 UTC, tbssajal approved these changes
LGTM