Oracle accountability finalize and autobond updates
autonity/autonity pull request #1073
Opened 2024-11-18 17:09 UTC by ScottRMalley

This PR includes:

- incorporation of Autobond into the Oracle rewards
- Refactored finalize() in Oracle.sol to separate voters' info update and rewards distribution from the function and call finalize() at the beginning of finalize() in Autonity.sol like accountability contracts.
- Bug fix in _findOutliers function when calculating ratio.

2024-11-19 13:52 UTC, tbssajal requested changes

2024-11-19 13:52 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +        config.contracts.oracleContract.distributeRewards{value: _atnOracleRewards}(_ntnOracleRewards);
Maybe use `accounts[address(config.contracts.oracleContract)]` instead of `_ntnOracleRewards`?

2024-11-19 13:52 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
>      uint256 private aggregatedScore;
Are we using this variable anymore?

2024-11-19 13:52 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
> +                voterInfo[_voter].performance = 0;
I am not sure if it falls under validator mismanagement but what if multiple validator nodes have single treasury address and single voter address? In that case we will count its performance only once where I am not sure if we should count it more than once. If we should count it more than once, we can set this `voterInfo[_voter].performance = 0` in a 2nd for loop.

2024-11-19 13:52 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
>              int256 _ratio = (_median - int256(uint256(reports[_symbol][_voter].price)) * 100) / _median;
```suggestion
            int256 _ratio = (_median - int256(uint256(reports[_symbol][_voter].price))) * 100 / _median;
```
I think the current formula is multiplying 100 with the price and then subtracting from median and then dividing by median. I think it is wrong. I guess it should be to subtract the price from the median first and then multiply with 100 and then divide by median. Also the other formula in `_penalize()` function does it this way.

2024-11-19 13:52 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
> +            rewardReceivers.remove(_voter);
I think removing should be done in another loop. Right now, remove function will change the order of the set. To be exact, the position at `i` will have a new address. So another way to handle it, if you want to do it in a single for loop, is doing `rewardReceivers.at(0)` instead of `rewardReceivers.at(i)` until set becomes empty.

2024-11-19 15:00 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
> +                voterInfo[_voter].performance = 0;
Single treasury address shouldn't be a problem because we only use it when sending ATN rewards. Single voter address would indeed be an issue. This would go beyond just how we are zeroing performance in this for loop, it would also be an issue in how we store `rewardsReceivers` as an `EnumerableSet.AddressSet` because we assume voter addresses are unique.

Is there any chance voter addresses would not be unique? Should that be allowed in the protocol? I was operating under the assumption that the same voter address would imply the same node address.

2024-11-19 15:02 UTC, ScottRMalley commented on autonity/solidity/contracts/Autonity.sol
> +        config.contracts.oracleContract.distributeRewards{value: _atnOracleRewards}(_ntnOracleRewards);
Yes great point. Had meant to do that. Updated now.

2024-11-19 15:02 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
>      uint256 private aggregatedScore;
No, it was used, but only to write to and never to read. I've removed it now.

2024-11-19 15:04 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
> +            rewardReceivers.remove(_voter);
Yeah that is a really good point. I missed that.

I've updated it now to loop through `rewardReceivers.values()` instead of using `at(i)`. I'm still thinking whether that is the best way to do this, as it could become a problem if we have a large set of voters.

2024-11-19 15:25 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
> +                voterInfo[_voter].performance = 0;
I don't think we have a check for voter address. So technically it is possible for different validator nodes to have same voter address. I am not sure if it is a mismanagement from the validator side or if we should handle this scenario. If we want to handle it, I think storing them in `rewardsReceivers` should not be an issue, as by the definition, it's a set. I guess only the map `rewardPeriodPerformance` should be updated properly. That's why I was suggesting to set `voterInfo[_voter].performance = 0` in a 2nd loop if we want to handle such scenario.

2024-11-19 15:34 UTC, tbssajal commented on autonity/solidity/contracts/Oracle.sol
> +            rewardReceivers.remove(_voter);
I guess using `rewardReceivers.at(0)` until the set becomes empty would avoid creating big list in memory. But current code is also fine for me. We create such big lists here and there very often.

2024-11-20 11:20 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Oracle.sol
>              _success = true;
Shoun't we set the `_price` after the aggregation is success?

2024-11-20 11:21 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Oracle.sol
> +        if (_count > 0) {
Shoun't we check the num of reports are at least 2/3 of the num of participants of consensus committee?

2024-11-20 12:38 UTC, lorenzo-dev1 commented on autonity/calls.go
> +		nodeAddresses = append(nodeAddresses, *val.NodeAddress)
There is a bug here, the slices are allocated with a length!=0 and then `append` is used, this will lead to having a bunch of empty spots at the start of the slice

2024-11-20 12:41 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Autonity.sol
> +        require(_votePeriod * 2 <= _period, "epoch period is too small");
Consider adding this check also for the genesis parameters (for example in the `Prepare` function)

2024-11-20 12:53 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Autonity.sol
> +
Just to understand, is there an economical reason for which the transfer of funds happens here and not anymore before? Or is it just for code cleanliness

2024-11-20 13:24 UTC, tbssajal approved these changes
LGTM

2024-11-20 13:36 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Autonity.sol
> +        require(_votePeriod * 2 <= _period, "epoch period is too small");
nevermind, I saw it is done at the oracle contract deployment

2024-11-20 13:59 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Oracle.sol
> +    function _finalizeRewards() onlyAutonity internal {
I think it shouldn't be `onlyAutonity` since the function is internal and called by the oracle cotnract

2024-11-20 14:19 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Oracle.sol
Am I right to assume that there could be voting period that is half in epoch x and half in epoch x+1, whose rewards will be distributed at the end of epoch x+1?

2024-11-20 14:43 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Oracle.sol
> +                voterInfo[_voter].performance = 0;
I understand how this works but why do we need the `rewardPeriodPerformance` mapping? Why not keeping to accumulate into the `voterInfo.performance` and reset it only at epoch end?

2024-11-20 14:44 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Oracle.sol
> +                voterInfo[_voter].performance = 0;
Is it to facilitate tracking per-round performance for the oracle nodes?

2024-11-20 15:01 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
>          config.votePeriod = _votePeriod;
No, I don't think so. Basically, we are persisting the rewards of every ended round and only distributing them at the end of the epoch. The only thing that would change when updating the voting period would be that fewer/more rounds would occur before the next reward distribution, but the accumulated rewards from previous rounds should not change.

2024-11-20 15:02 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
Yes that is correct. Rewards are distributed based on the rounds that ended during the epoch that is finalized, so when the round was started is not considered in reward distribution.

2024-11-20 15:13 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
> +                voterInfo[_voter].performance = 0;
Yeah the idea was to have a variable that represented this round's performance, and another one to represent the aggregated epoch performance so that they could be tracked. That being said, on a second look, the voter performance will be incremented and set to zero in the same finalize transaction, so there's never any time to read round performance.

I think the best thing to do is to get rid of the mapping. Will update.

2024-11-20 15:14 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
> +                voterInfo[_voter].performance = 0;
Oh, wait, no I remember now, the voter info is deleted when a new voter set is added, so we need the mapping in order to keep track of rewards between epochs.

2024-11-20 15:18 UTC, ScottRMalley commented on autonity/solidity/contracts/Oracle.sol
> +    function _finalizeRewards() onlyAutonity internal {
Good point. Fixed.

2024-11-20 15:42 UTC, lorenzo-dev1 approved these changes
LGTM

2024-11-20 15:48 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Oracle.sol
>          config.votePeriod = _votePeriod;
But what about the `NewRound` event? In case of period change it will not be accurate anymore. And I think this is tracked by the oracle, right @Jason-Zhangxin-Chen

2024-11-21 08:30 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Oracle.sol
> +                voterInfo[_voter].performance = 0;
thanks

2024-11-21 10:15 UTC, merged