fix, grant autonity.slash() to oracle contract.
autonity/autonity pull request #1087
Opened 2024-11-24 06:56 UTC by Jason-Zhangxin-Chen

This PR contain corrections for oracle accountability.

2024-11-25 09:09 UTC, lorenzo-dev1 requested changes

2024-11-25 09:09 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Slasher.sol
> +
I don't think this is the right solution, because when slashing 100% we should jailbound, otherwise it can lead to other problems down the line. 

So either:
1. we cap the slashing in the oracle contract
2. we create a new function like `slashUnbounded` or something like that, which allows 100% slash and jailbounds the validator if 100% slash happens

2024-11-26 14:09 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Slasher.sol
> +
> I don't think this is the right solution, because when slashing 100% we should jailbound, otherwise it can lead to other problems down the line.
> 
> So either:
> 
> 1. we cap the slashing in the oracle contract
> 2. we create a new function like `slashUnbounded` or something like that, which allows 100% slash and jailbounds the validator if 100% slash happens

Thank you, Lorenzo. I think capping the slashing rate would be the best option.

2024-11-27 09:27 UTC, ScottRMalley approved these changes
This LGTM with the latest slashing rate cap changes.

2024-11-27 09:32 UTC, tbssajal approved these changes
LGTM except some minor comments.

2024-11-27 09:32 UTC, tbssajal commented on autonity/solidity/contracts/ProtocolConstants.sol
> +uint256 constant ORACLE_SLASHING_RATE_CAP = 1_000; // Capped with 10% slashing rate for oracle accountability.
Can we write `ORACLE_SLASHING_RATE_CAP = SLASHING_RATE_PRECISION / 10` instead or is it not allowed due to being constant?

2024-11-27 09:32 UTC, lorenzo-dev1 approved these changes
LGTM as well

2024-11-27 15:57 UTC, yazzaoui approved these changes
LGTM but we'll need later for the max slashing rate to be a governance parameter

2024-11-27 16:02 UTC, merged