Add Find(Fast)InvalidSignatures which locates invalid BLS signatures
autonity/autonity pull request #893
Opened 2023-12-04 17:08 UTC by m4ksio

2023-12-05 06:26 UTC, tbssajal requested changes
According to the logic of the base case (2 signatures), you are handling both start and end signatures. Then `pivot` is repeated in both left and right functions.

2023-12-05 06:26 UTC, tbssajal commented on crypto/bls/bls.go
> +		if start-end == 1 {
Is it `end-start == 1`. Or in this case you can simply write `start < end`

2023-12-05 06:26 UTC, tbssajal commented on crypto/bls/bls.go
> +				rightInvalid, rightErr = findInvalidSignaturesRecursive(signatures, pks, msgs, pivot, end)
I think it should be pivot+1

2023-12-05 06:26 UTC, tbssajal commented on crypto/bls/bls.go
> +			aggSig := AggregateSignatures(signatures[pivot:end])
I think it should be `[pivot+1][end+1]`

2023-12-05 06:26 UTC, tbssajal commented on crypto/bls/bls.go
> +			verified := aggSig.AggregateVerify(pks[pivot:end], msgs[pivot:end])
I think it is `[pivot+1][end+1]`

2023-12-05 06:26 UTC, tbssajal commented on crypto/bls/bls.go
> +			aggSig := AggregateSignatures(signatures[start:pivot])
I think it should be `pivot+1`

2023-12-05 06:26 UTC, tbssajal commented on crypto/bls/bls.go
> +			verified := aggSig.AggregateVerify(pks[start:pivot], msgs[start:pivot])
I think it is `pivot+1`

2023-12-13 00:37 UTC, m4ksio commented on crypto/bls/bls.go
> +			aggSig := AggregateSignatures(signatures[start:pivot])
Hmm, why?
Here we check `<start, pivot)` and next half checks `<pivot, end)` which covers entire range (since end is len of array so last index + 1.

2023-12-13 01:07 UTC, m4ksio commented on crypto/bls/bls.go
> +		if start-end == 1 {
Funny thing. 
This if is not really used anyway, since there is a bug in line 107 (or maybe not bug, since overall algorithms works OK). It only gets true for a single element slice. If it changes to match the comment and trigger for two items - than indeed, line 116 is wrong and tests no longer pass.
So since line 107 should be `end-start <= 2` this cannot be simply changed to `start < end` but it should be `end-start == 2` indeed. 
Having those both changed now add a nice speedup - worst case scenario in benchmark went from 634ms to 593ms! Really good find!

2023-12-13 05:19 UTC, tbssajal commented on crypto/bls/bls.go
> +			aggSig := AggregateSignatures(signatures[start:pivot])
Okay I see, start is included and end is excluded in your function.

2023-12-13 05:22 UTC, tbssajal requested changes
Just to be safe, maybe add another case.

2023-12-13 05:22 UTC, tbssajal commented on crypto/bls/bls.go
> +	if end-start <= 2 {
So in this start is included and end is excluded, that case there should be another case before this one just to be safe: `if start >= end` it should return an empty list.

2023-12-14 21:40 UTC, m4ksio commented on crypto/bls/bls.go
> +	if end-start <= 2 {
I don't think its necessary. This is an internal function and we control how parameters are passed. 
But even if for whatever reason `start` will become larger than `end` the worst that can happen is simply an extra verification. I don't think this justified extra safety check.

However, since start and end are indices, and we also return indices of invalid signatures, I have changed the type to `uint` so we can't even have negative numbers

2023-12-18 16:37 UTC, lorenzo-dev1 commented
@m4ksio Is there somewhere where I can see the results of this benchmark?

2023-12-19 13:34 UTC, tbssajal commented on crypto/bls/bls.go
> +	if end-start <= 2 {
Yeah, I see you already put a check on the array size before calling the function

2023-12-19 17:05 UTC, m4ksio commented
> @m4ksio Is there somewhere where I can see the results of this benchmark?

In the issue https://github.com/autonity/autonity/issues/883
Updated description with this link

2023-12-22 07:55 UTC, tbssajal approved these changes
Just some minor comments. Except that LGTM

2023-12-22 07:55 UTC, tbssajal commented on crypto/blst/find_invalid_benchmark_test.go
> +		if len(invalid) != len(failedNs) {
maybe we could do this sort of checks in separate tests and keep the benchmark free of extra work that may add to runtime. Besides I think any concerns should be addressed in tests, because benchmarks are not run in checks.

2023-12-22 07:55 UTC, tbssajal commented on crypto/blst/find_invalid_benchmark_test.go
> +func benchmarkAggregatePK(seed int64, n int, b *testing.B) {
It seems like `seed` and `n` are unnecessary input parameters.

2024-01-10 03:14 UTC, m4ksio commented on crypto/blst/find_invalid_benchmark_test.go
> +		if len(invalid) != len(failedNs) {
They are rater miniscule in this case, but I agree with principle, removed.

2024-01-10 03:15 UTC, m4ksio commented on crypto/blst/find_invalid_benchmark_test.go
> +func benchmarkAggregatePK(seed int64, n int, b *testing.B) {
`n` is used, `seed` is not indeed, Removed `seed`

2024-03-28 11:26 UTC, lorenzo-dev1 commented
I cherry picked the functions to find invalid signatures and the related benchmarks and tests on top of https://github.com/autonity/autonity/pull/966 (BLS aggregator PR)

2024-05-31 09:03 UTC, lorenzo-dev1 commented
I think this PR can be closed. I cherry-picked all the useful code in https://github.com/autonity/autonity/pull/957

2024-06-11 14:36 UTC, lorenzo-dev1 commented
Closing as obsolete

2024-06-11 14:36 UTC, closed without merging