Config update for R5
autonity/autonity pull request #948
Opened 2024-02-23 03:39 UTC by yazzaoui

@cmjc @raj-shekhar1 Please review

2024-02-23 09:16 UTC, lorenzo-dev1 approved these changes
LGTM in terms of code changes, but I did not check if the validator cryptographic data is correct.

2024-02-23 09:21 UTC, lorenzo-dev1 requested changes
@yazzaoui actually we need also to uncomment the piece of code about bls key unmarshalling in params/protocol_contracts.go Validate() function.

2024-02-23 09:33 UTC, cmjc approved these changes
LGTM. @lorenzo-dev1 - @spenot09 and @raj-shekhar1 verified the provided validator from the Community GV's when it was provided 👍

2024-02-23 11:17 UTC, cmjc requested changes
The chain and network Id is 65100002 - see https://github.com/autonity/project-execution/edit/main/APRs/APR-25.md

2024-02-23 11:17 UTC, cmjc commented on params/config.go
>  		ChainID:                 big.NewInt(65_100_001),
```suggestion
		ChainID:                 big.NewInt(65_100_0012),
```

Per APR25, the chain and network ID is `65100002`

2024-02-23 11:20 UTC, cmjc commented on params/config.go
>  		ChainID:                 big.NewInt(65_100_001),
@yazzaoui - note also per https://github.com/ethereum-lists/chains/pull/4346 for Bakerloo Testnet it is changed to:

```
"chainId": 65010002,
"networkId": 65010002,
```

2024-02-23 13:12 UTC, raj-shekhar1 commented
I am confirming the GV details, will update here.

2024-02-23 18:07 UTC, raj-shekhar1 commented
> I am confirming the GV and bootnode details, will update here.

LGTM, Thanks

2024-02-23 18:08 UTC, raj-shekhar1 approved these changes

2024-02-23 22:18 UTC, lorenzo-dev1 approved these changes
LGTM

2024-02-26 10:39 UTC, cmjc requested changes
@yazzaoui - edits for the GV bondedStake amounts

2024-02-26 10:39 UTC, cmjc commented on params/config.go
> +					BondedStake:   Ntn10000,
```suggestion
					BondedStake:   Ntn1,
```

Changing from `Ntn10000` to `NTN1` as requested by @spenot09

2024-02-26 10:39 UTC, cmjc commented on params/config.go
> +					BondedStake:   Ntn10000,
```suggestion
					BondedStake:   Ntn1,
```

Changing from `Ntn10000` to `NTN1` as requested by @spenot09

2024-02-26 10:39 UTC, cmjc commented on params/config.go
> +					BondedStake:   Ntn10000,
```suggestion
					BondedStake:   Ntn1,
```

Changing from `Ntn10000` to `NTN1` as requested by @spenot09

2024-02-26 17:22 UTC, merged