[WIP]Test fw improvements
autonity/autonity pull request #950
Opened 2024-02-28 11:27 UTC by Jason-Zhangxin-Chen

2024-05-15 20:37 UTC, lorenzo-dev1 requested changes
Awesome work! `upon_condition` tests looks much better and the collusion framework looks awesome!

I left few comments, the only one blocking for merging is [this one](https://github.com/autonity/autonity/pull/950#discussion_r1602203595) related to some important accountability tests that were lost while refactoring.

Additionally, I think that we need a better way to check that misbehaving nodes get disconnected at p2p level. A lot of our DoS defence relies on this. I left a comment [here](https://github.com/autonity/autonity/issues/873#issuecomment-2113411585) to track this, it can be done in a separate PR.

2024-05-15 20:37 UTC, lorenzo-dev1 commented on consensus/tendermint/core/upon_condition_test.go
> +					VotingPower: e.committee.F(),
I think here the power we levels we were using are different wrt to the new refactored version. Is this test still correct?

2024-05-15 20:37 UTC, lorenzo-dev1 commented on consensus/tendermint/core/upon_condition_test.go
> +					VotingPower: e.committee.F(),
same here

2024-05-15 20:37 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/fault_detector_test.go
> -	t.Run("RunRule address the Accusation of PO rule, no quorum preVotes presented on the valid round BUT proposal was committed", func(t *testing.T) {
I think that in the refactor we lost the test that were checking that no accusation is raised if the block has been committed. It is important that we re-add this kind of tests, we want to avoid that nodes raise useless accusations. 

see https://github.com/autonity/autonity/blob/develop/consensus/tendermint/accountability/fault_detector.go#L827

2024-05-16 09:10 UTC, vpiyush commented on .github/workflows/go.yml
> +      - run: go test -v -run ${{ matrix.tests }} ./e2e_test/byzantine/... -timeout 30m
Isn't the 30 min timeout too high for this considering we have whole ci running under 10m now

2024-05-16 09:11 UTC, vpiyush commented on .github/workflows/go.yml
> +      - run: go test -v -run ${{ matrix.tests }} ./e2e_test/byzantine/... -timeout 30m
Also what do you thing about adding a race flag to all of these tests. I think it's of value to do that.

2024-05-16 09:20 UTC, vpiyush commented on consensus/tendermint/accountability/fault_detector_test.go
> +	height := uint64(0)
It's worth adding some comments in the test case to indicate what we are doing

2024-05-16 09:21 UTC, vpiyush commented on consensus/tendermint/accountability/fault_detector_test.go
> +	t.Run("misbehaviour when pi has sent a non-nil precommit in a previous round", func(t *testing.T) {
what's pi, It will be helpful to use non-abbreviated terms in messages.

2024-05-16 11:10 UTC, vpiyush commented on e2e_test/byzantine/accountability_network_test.go
> -	// the challenger should get no peer connection left.
Here is my understanding of this: 
IMO We don't have a logic to wait for 30 second for the peer we disconnected. We do have inbound connection attempt logic but that's for DDOS of connection attempts . Also we have dial checks which are done every 5 seconds, these are also for dial attempts. In this test case what could happen is we disconnect the peer and either we wait for less than 5 seconds if last dial was not expired OR we immediately dial again. and get connected back.
So, I would think we need to add Jail time here. whenever we disconnect a peer which should ensure 30 second (Or Whatever jailing time we choose) delay in next successful connection.
In conlusion - in this test we should bring back the client connection count logic and rely on server jailing for peer to remain disconnected.

2024-05-16 11:10 UTC, Jason-Zhangxin-Chen commented on e2e_test/byzantine/garbage_and_fuzz_test.go
> +		precommit = message.NewPrecommit(r, h, common.Hash{}, c.Backend().Sign)
> These tests do not fuzz the signature field. Is that covered in some other test?

I will add a todo to track the missing fuzz of signature field in consensus messages.

2024-05-16 11:12 UTC, vpiyush commented on e2e_test/byzantine/accountability_network_test.go
> -	// the challenger should get no peer connection left.
> 1. The disconnection doesn't happen if the malicious sender is locally connected (i.e. has a LAN address such as 127.0.0.0)

Also, I don't see this. We do disconnect irrespetive of whether we are connected on loopback. Though this is applicable to inbound connection attempts.

2024-05-16 11:17 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/upon_condition_test.go
> +		if e.curRound == 0 {
> I think we don't need this if condition since the `curRound` is not randomized anymore in this test?

Yes, the default value is 0 for curRound unless we set a random one. In this context, we can remove the checker now.

2024-05-16 11:30 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/upon_condition_test.go
> +					VotingPower: e.committee.F(),
> I think here the power we levels we were using are different wrt to the new refactored version. Is this test still correct?

Hi Lorenzo, could you be more specific? Do you the new version with msg aggregation?

2024-05-16 11:34 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/upon_condition_test.go
> +					VotingPower: e.committee.F(),
> same here

I guess you mean the voting power is resloved by the preValidate() and Validate(), thus we'd need a new way to level the voting power in our bls-aggregation branch.

2024-05-16 11:42 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/ape-config.yaml
> +solidity:
> is this branch not rebased correctly, these changes were also part of other PR??

It haven't been rebased yet.

2024-05-16 11:47 UTC, lorenzo-dev1 commented on e2e_test/byzantine/accountability_network_test.go
> -	// the challenger should get no peer connection left.
we do disconnect but then the inbound check is skipped: https://github.com/autonity/autonity/blob/develop/p2p/server.go#L1057

So basically the malicious peer can re-connect right away

2024-05-16 11:50 UTC, lorenzo-dev1 commented on consensus/tendermint/core/upon_condition_test.go
> +					VotingPower: e.committee.F(),
No, I mean the new power is F while in the old code (before your changes) it was F-1

2024-05-16 11:53 UTC, lorenzo-dev1 commented on e2e_test/byzantine/accountability_network_test.go
> -	// the challenger should get no peer connection left.
In any case yes I think we need a more reliable disconnection mechanism through jailing, it should be a high priority feature imo.

2024-05-16 11:55 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector_test.go
> +	t.Run("misbehaviour when pi has sent a non-nil precommit in a previous round", func(t *testing.T) {
`pi` in the context stands for a consensus participant with an unique identity `i`, it is adopt from the tendermint paper and the accountability paper work. I will add this in the context explaination comment in rule engine.

2024-05-16 12:07 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/innocence_proof_handler.go
> +	fd.logger.Info("Withdraw accusation", "rule", proof.Rule, "suspected account", proof.Message.Sender())
resolved in a9708ffe0daf2adb42668b9b066df55d82d43ca0

2024-05-16 12:08 UTC, Jason-Zhangxin-Chen commented on e2e_test/byzantine/accountability_network_test.go
> +		// since our RLP encoding of accusation msg does not allow a full proposal, thus we skip the proposal code.
resolved in a9708ffe0daf2adb42668b9b066df55d82d43ca0 by adding todo to track it.

2024-05-16 12:10 UTC, Jason-Zhangxin-Chen commented on e2e_test/byzantine/accountability_network_test.go
> -	// the challenger should get no peer connection left.
resolved in a9708ffe0daf2adb42668b9b066df55d82d43ca0 by adding todo to track this, in that todo, I suggested to create a framework to test the peer drop/reconection events, for the time being, we don't have such framework yet.

2024-05-16 12:16 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/upon_condition_test.go
> +					VotingPower: e.committee.F(),
Oh, I see. The new voting power leveled is correct with the new refacted test framework, we have to make sure the total power of a new round is over F().

2024-05-16 12:16 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/upon_condition_test.go
> +					VotingPower: e.committee.F(),
See my last reply.

2024-05-16 12:17 UTC, Jason-Zhangxin-Chen commented on .github/workflows/go.yml
> +      - run: go test -v -run ${{ matrix.tests }} ./e2e_test/byzantine/... -timeout 30m
Resolved in a9708ffe0daf2adb42668b9b066df55d82d43ca0

2024-05-16 12:18 UTC, Jason-Zhangxin-Chen commented on .github/workflows/go.yml
> +      - run: go test -v -run ${{ matrix.tests }} ./e2e_test/byzantine/... -timeout 30m
Resolved in a9708ffe0daf2adb42668b9b066df55d82d43ca0

2024-05-16 12:19 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector_test.go
> +	height := uint64(0)
Resolved in a9708ffe0daf2adb42668b9b066df55d82d43ca0, by adding some comments.

2024-05-16 13:00 UTC, lorenzo-dev1 commented on consensus/tendermint/core/message/message.go
> +	FakeRound     uint64
yeah, actually I realize now that this is `round`, not `validRound`. So it is actually correct for it to be uint

2024-05-16 13:12 UTC, vpiyush commented on e2e_test/byzantine/accountability_network_test.go
> -	// the challenger should get no peer connection left.
> we do disconnect but then the inbound check is skipped: https://github.com/autonity/autonity/blob/develop/p2p/server.go#L1057
> 
> So basically the malicious peer can re-connect right away

Inbound check is only for connection attempts, so whether it get's skipped or not. For a peer who was connected to us more than 30 seconds(or we will dial to it if it was connected for more than 5 seconds) will always get connected even if not on LAN.

2024-05-16 13:29 UTC, lorenzo-dev1 commented on e2e_test/byzantine/accountability_network_test.go
> -	// the challenger should get no peer connection left.
opened issue to track this https://github.com/autonity/autonity/issues/983, it is important

2024-05-16 13:29 UTC, lorenzo-dev1 approved these changes

2024-05-16 15:40 UTC, vpiyush approved these changes

2024-05-16 16:22 UTC, yazzaoui approved these changes
I haven’t delved into the details of this PR, but at a glance, it looks good. We might need some refinements later—I have a few ideas. For now, it’s a solid improvement to our testing suite. LGTM.

2024-05-17 04:19 UTC, merged