[WIP] feature, reimburse accountability events.
autonity/autonity pull request #965
Opened 2024-03-21 11:49 UTC by Jason-Zhangxin-Chen

2024-06-03 09:39 UTC, vpiyush commented on autonity/solidity/contracts/Accountability.sol
> +            allowedReporters[committee[i].addr] = true;
Do we really need to maintain this? In the autonity contract we do the similar checks by looping to the existing committee.( _incommittee modifier)

2024-06-03 10:36 UTC, vpiyush commented on autonity/solidity/contracts/Accountability.sol
> +        delete curCommittee;
Is this delete required?

2024-06-03 10:36 UTC, vpiyush commented on autonity/solidity/contracts/Accountability.sol
> +        delete lastCommittee;
is this delete required?

2024-06-04 11:22 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Accountability.sol
> +        delete curCommittee;
> Is this delete required?

Resolved in 46487abf9840bcdfe48a4f2e85b041548ae78117

2024-06-04 11:22 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Accountability.sol
> +        delete lastCommittee;
> is this delete required?

Resolved in https://github.com/autonity/autonity/commit/46487abf9840bcdfe48a4f2e85b041548ae78117

2024-06-14 15:19 UTC, lorenzo-dev1 requested changes
Overall LGTM, few comments here and there!

2024-06-14 15:19 UTC, lorenzo-dev1 commented on core/state_transition.go
> +			// todo: make accusation event future reimbursable?
I think we can discuss this at standup too

2024-06-19 15:01 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/reporter.go
> +			fd.logger.Warn("Accountability transaction sent", "tx", tx.Hash(), "gas", tx.Gas(), "size", tx.Size())
Resolved in 7deef3fbd6372e11e2ad4996a65ce574515951b9

2024-06-19 15:01 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/reporter.go
> +			for ; attempt < MaxSubmissionAttempts; attempt++ {
Resolved in 7deef3fbd6372e11e2ad4996a65ce574515951b9

2024-06-19 15:01 UTC, Jason-Zhangxin-Chen commented on autonity/tests/accusations_test.go
> +		r.run("PVN accusation with prevote nil should revert", func(r *runner) {
Resolved in 7deef3fbd6372e11e2ad4996a65ce574515951b9

2024-06-21 10:55 UTC, lorenzo-dev1 requested changes
Small comments here and there + 2 major points:
1. In the `AggregateDistinctPrecommits` we do not need to aggregate the precommits for same (r,v). We can arbitrarly pick one, since we are just interested in inserting one precommit from the offender in the proof. We do not care about maximizing the number of signers.
2. In PVO12 we can actually have a single precommit as proof, in this case:
```
vr = 0
currentR = 2
```

and in round=1 we have precommit not for V. Here we will raise a proof with a single precommit as evidence.

2024-06-21 10:55 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/contracts.go
> +	if p.DistinctPrecommits.Len() > 0 {
We need the case for a single precommits as proof

2024-06-21 10:55 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +	r.Round = int64(ext.Round)
We can have a boundary check on the round when decoding (like we do for the consensus messages). Moreover we can also check that we have at least one signer.

2024-06-21 10:55 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/contracts_test.go
> -			// vote for nil value
Shouldn't this still fail?

2024-06-23 02:50 UTC, Jason-Zhangxin-Chen commented
> Small comments here and there + 2 major points:
> 
> 1. In the `AggregateDistinctPrecommits` we do not need to aggregate the precommits for same (r,v). We can arbitrarly pick one, since we are just interested in inserting one precommit from the offender in the proof. We do not care about maximizing the number of signers.
> 2. In PVO12 we can actually have a single precommit as proof, in this case:
> 
> ```
> vr = 0
> currentR = 2
> ```
> 
> and in round=1 we have precommit not for V. Here we will raise a proof with a single precommit as evidence.

Thank you so much, Lorenzo. They were resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:51 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +func FastAggregatePrevotes(prevotes []*message.Prevote) *message.Prevote {
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:51 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:51 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:51 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:52 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +				proof.DistinctPrecommits = AggregateDistinctPrecommits(precommitsFromPi)
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:52 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector_test.go
> +		require.NoError(t, err)
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:52 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector_test.go
> +		require.NoError(t, err)
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:54 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector_test.go
> +
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:54 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector_test.go
> +		require.NoError(t, err)
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:54 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector_test.go
> +		require.NoError(t, err)
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:54 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +	if len(p.Evidences) != 1 {
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:54 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:54 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +	_, ok := r.hasSigners[index]
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:55 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +	for _, m := range h.RoundValueSigners {
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:55 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +type RoundValueSigners struct {
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:56 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +func AggregateDistinctPrecommits(precommits []*message.Precommit) HighlyAggregatedPrecommit {
The comment was there, how ever I refine it in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:56 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +	}
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:56 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +	if p.DistinctPrecommits.Len() > 0 {
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 02:56 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +	r.Round = int64(ext.Round)
resolved in 1c7bbb5b01d288d8f3d4bf2a29a2b28a3e24fb47

2024-06-23 06:13 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts_test.go
> -			// vote for nil value
> Shouldn't this still fail?

This case is removed due to the duplicated with the last test.

2024-06-23 06:20 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector_test.go
> +			}
It is about to aggregate the required precommits between the valid round to currrent round as an expected output, thus we can compare the actual proof with this expected one.

2024-06-24 09:42 UTC, lorenzo-dev1 requested changes
Mostly LGTM now but there are two bugs in the duplicated message detection imo

2024-06-24 09:48 UTC, lorenzo-dev1 commented on autonity/solidity/contracts/Accountability.sol
> +        uint256 _cap = (curCommittee.length-1)*(uint256(Severity.Mid)+1);
Re-think about it, I think this is fine for the moment. It is anyways hard to spam accusation because you have to use a message that was not for a committed block.

2024-06-27 15:00 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +		presentedMsgs[m.Round] = make(map[common.Hash]struct{})
resolved in 4c9a1431b8c130ee21cb79e4b2742eb2db69280e

2024-06-27 15:00 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +		if lastPrecommit.R() == precommits[i].R() &&
resolved in 4c9a1431b8c130ee21cb79e4b2742eb2db69280e, thank you Lorenzo.

2024-06-27 15:15 UTC, lorenzo-dev1 approved these changes
LGTM!!!

2024-07-25 11:46 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/contracts.go
> +	if len(p.Evidences) < 2 {
I think the previous checker was correct, we can have len(p.Evidences) == 1 if we have the proposal in the evidece and then we have the aggregated precommit in `p.DistinctsPrecommits`

2024-09-19 08:13 UTC, vpiyush commented on autonity/solidity/contracts/Accountability.sol
> +    function setCommittee(address[] memory _newCommittee) external onlyAutonity{
Could we do something like this here, to reduce storage writes  in setCommittee, instead of removing access from everyone and giving access to everyone again,  something like below:

for each member in CurCommittee:
   if notInNewCommittee:
        //remove access
for each member in newCommittee:
   if notInCurrCommitt:
        // grant access

By doing this we only update the difference of committees. Also we would not need to maintain last committee only it's length for other place where it is being used.

2024-09-19 12:15 UTC, vpiyush commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +	for _, m := range h.MsgSigners {
do we need a nil check for msgSigners?

2024-09-19 12:25 UTC, vpiyush commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +		if _, ok := presentedMsgs[precommits[i].R()][precommits[i].Value()]; !ok {
optimization: avoid muliple map lookups, you can save the result from the first lookup and use the same here

2024-09-19 12:26 UTC, vpiyush commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +			presentedMsgs[precommits[i].R()][precommits[i].Value()] = struct{}{}
same here

2024-09-19 12:59 UTC, vpiyush commented on consensus/tendermint/accountability/fault_detector.go
> +	evidences[0] = prevotes[0]
don't we need the nil and length check for prevotes before accessing?

2024-09-19 13:34 UTC, vpiyush commented on consensus/tendermint/accountability/fault_detector.go
> +	evidences[0] = prevotes[0]
similar issue at line 456

2024-09-19 13:58 UTC, vpiyush commented on consensus/tendermint/accountability/reporter.go
> +			panic("Skip unknown accountability event")
Do we really need to panic here? Can an erro log suffice here. I am afraid that we are overusing Panic. it seems to be in lot more places in the code now. Ideally should only be exceptional scenarios. thoughts?

2024-09-19 14:36 UTC, vpiyush commented on core/state_transition.go
> +func resolveReimburseType(msg Message) int {
I think it's more of a boolean function isReimbusable. Not sure if there is a need of integer return. please recheck that could be easier

2024-09-20 05:49 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +	for _, m := range h.MsgSigners {
> do we need a nil check for msgSigners?

No, we did such check before run into prevalidate() and validate() of highlyAggregatedPrecommits by checking if the highlyAggregatedPrecomits contains signers with:
```
if p.DistinctPrecommits.Len() > 0 {}
```

2024-09-20 06:36 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +	evidences[0] = prevotes[0]
Good catch, although we checked over quorum prevotes for old proposal at vr, however due to off-chain accusation handler runs in different routine, thus GC of msg store could potentially delete the prevotes. We need to check it again.

2024-09-20 06:42 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/reporter.go
> +			panic("Skip unknown accountability event")
We need to unify this thought, as we discussed before, to panic to address those impossible scenarios ASAP. I think we need to evaluate the degree of such cases, for those ones which does not impact the safety or livness of the chain, a logging might be better, however for those ones which impact the safety and livness, a panic should be a good one.

2024-09-20 07:12 UTC, Jason-Zhangxin-Chen commented on core/state_transition.go
> +	if msg.To() != nil && *msg.To() == params.OracleContractAddress {
I remove it by using the contractCreation flag saved in the caller side.

2024-09-20 07:16 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +		if _, ok := presentedMsgs[precommits[i].R()][precommits[i].Value()]; !ok {
Resolved in 5246eb9ba213c607a0ed2a7c21a41685e3be32cd

2024-09-20 07:17 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/distinct_msg_aggregator.go
> +			presentedMsgs[precommits[i].R()][precommits[i].Value()] = struct{}{}
Resolved in 5246eb9ba213c607a0ed2a7c21a41685e3be32cd

2024-09-20 07:17 UTC, Jason-Zhangxin-Chen commented on core/state_transition.go
> +func resolveReimburseType(msg Message) int {
Resolved in 5246eb9ba213c607a0ed2a7c21a41685e3be32cd

2024-09-20 08:19 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Accountability.sol
> +    function setCommittee(address[] memory _newCommittee) external onlyAutonity{
The initial logic I took was computing the diffs, however as mapping cannot be created dynamically in solidity, iterating the two sets to compute the differences is slow especially when we have big set of committee, and moreover that it makes the code not lean as well. Current logic looks lean and simple, I made a little improvement in writing the storage of reporters here: f5695b5161b65da257c32a68e464fd60e6f80b59

2024-09-20 11:12 UTC, vpiyush reviewed
LGTM!!

2024-09-20 11:22 UTC, Jason-Zhangxin-Chen commented
> LGTM!!

Thank you so much, please click the `approve` then I can get the PR be ready for merging.

2024-09-20 12:16 UTC, vpiyush approved these changes

2024-09-25 08:53 UTC, merged