Fixed buffered metrics, Added new metrics
autonity/autonity pull request #974
Opened 2024-04-23 11:02 UTC by vpiyush

In This PR, following changes are done:
- Fixed buffered metrics to avoid memory leak, fixed buffer sizes for the counters
- Added new metrics in system 
- optimized memory intensive metrics (removed sprintf)
- Lazy logging for expensive logs
- changes in backend handler
     - no message discarding
     - remove payload copy before message handling
     - cache lookup are moved into go-routine, so not to delay the next read

2024-05-09 09:45 UTC, lorenzo-dev1 reviewed
Everything looks good, except that maybe there is some missing code for Prometheus export?

2024-05-09 09:45 UTC, lorenzo-dev1 commented on metrics/buffered_gauge.go
> +		g.rIndex = g.rIndex % g.capacity
does `rIndex` stand for `replaceIndex`? Because now the bufferedgauge is a circular buffer?

2024-05-09 09:45 UTC, lorenzo-dev1 commented on consensus/acn/protocol/peer.go
> +func getWriteMetric(msgCode uint64) metrics.BufferedGauge {
Why `Write`? I would rename to `getMetric` or even just `metric`.

2024-05-09 09:45 UTC, lorenzo-dev1 commented on consensus/tendermint/core/metrics.go
> +func getIntPointer(val int) *int {
Not a big deal but since I saw already two declaration of this func it might be worth to put it into a `helpers` function somewhere. Or maybe in the metrics package itself.

2024-05-09 09:45 UTC, lorenzo-dev1 commented on consensus/tendermint/core/precommit.go
> +		"currentProposer", log.Lazy{Fn: func() types.CommitteeMember { return c.CommitteeSet().GetProposer(c.Round()) }},
Just curious, is the function wrapping needed to defer also the inner `c.Round()` call?

2024-05-09 09:45 UTC, lorenzo-dev1 commented on metrics/exp/exp.go
> -			//TODO:
Why don't need  anything here?

2024-05-09 09:45 UTC, lorenzo-dev1 commented on metrics/prometheus/prometheus.go
> -				// TODO: need to add support for bufferedGauge to correct prometheus type
We don't need anything here?

2024-05-09 12:05 UTC, vpiyush commented on metrics/buffered_gauge.go
> +		g.rIndex = g.rIndex % g.capacity
yes, essentially its a circular buffer now. We have a capacity requirement when creating the metric at that point it's user responsibility to allocate the max capacity for the metric,

2024-05-09 12:05 UTC, vpiyush commented on consensus/acn/protocol/peer.go
> +func getWriteMetric(msgCode uint64) metrics.BufferedGauge {
this is because getWriteMetric is only fetching the socket write related metrics.

2024-05-09 12:06 UTC, vpiyush commented on consensus/tendermint/core/metrics.go
> +func getIntPointer(val int) *int {
sure

2024-05-09 12:12 UTC, vpiyush commented on metrics/exp/exp.go
> -			//TODO:
Ok, the idea is to not throw any errors on buffered gauge when metrics are being fetched with proemtheus client. we established that it's ok to only support the buffered gauge with influx db but we must not throw any errors on prometheus

2024-05-09 12:12 UTC, vpiyush commented on metrics/prometheus/prometheus.go
> -				// TODO: need to add support for bufferedGauge to correct prometheus type
see response above

2024-05-09 12:13 UTC, vpiyush commented
> Everything looks good, except that maybe there is some missing code for Prometheus export?

Chec response [here](https://github.com/autonity/autonity/pull/974#discussion_r1595365112)

2024-05-09 12:18 UTC, vpiyush commented on consensus/tendermint/core/precommit.go
> +		"currentProposer", log.Lazy{Fn: func() types.CommitteeMember { return c.CommitteeSet().GetProposer(c.Round()) }},
no, because c.Round() is only evaluated when outer function is invoked and which would be invoked on log construction.

2024-05-09 13:14 UTC, lorenzo-dev1 commented on consensus/acn/protocol/peer.go
> +func getWriteMetric(msgCode uint64) metrics.BufferedGauge {
It is not very clear, because the reader doesn't know that Write is an adjective. I thought this function would Write something because I interpreted it as a verb

2024-05-09 13:15 UTC, lorenzo-dev1 commented on consensus/tendermint/core/precommit.go
> +		"currentProposer", log.Lazy{Fn: func() types.CommitteeMember { return c.CommitteeSet().GetProposer(c.Round()) }},
Then why the wrapping into a `func()`

2024-05-09 14:48 UTC, vpiyush commented on consensus/tendermint/core/precommit.go
> +		"currentProposer", log.Lazy{Fn: func() types.CommitteeMember { return c.CommitteeSet().GetProposer(c.Round()) }},
If you directly pass it would become function call, and evaluate immediately. So when there is an argument we need to wrap it under func to defer execution.

2024-05-09 14:50 UTC, vpiyush commented on consensus/acn/protocol/peer.go
> +func getWriteMetric(msgCode uint64) metrics.BufferedGauge {
Since it's a local function it won't matter much, what do you think about getMsgWriteMetric OR getSockeWriteMetric?

2024-05-09 15:05 UTC, lorenzo-dev1 commented on consensus/acn/protocol/peer.go
> +func getWriteMetric(msgCode uint64) metrics.BufferedGauge {
`getSocketWriteMetric`? I would still remove the `get` since it shouldn't be used in go I think

Anyways not a big deal you can even leave it like this

2024-05-09 15:05 UTC, lorenzo-dev1 approved these changes
LGTM

2024-05-13 10:57 UTC, tbssajal requested changes

2024-05-13 10:57 UTC, tbssajal commented on consensus/tendermint/backend/engine.go
> +		sealDelayBg.Add(delay.Nanoseconds())
Can delay be negative here?

2024-05-13 10:57 UTC, tbssajal commented on consensus/tendermint/backend/engine.go
> +		sealDelayBg.Add(delay.Nanoseconds())
Assuming it was created before `now()`, I guess it can be negative.

2024-05-13 13:03 UTC, vpiyush commented on consensus/tendermint/backend/engine.go
> +		sealDelayBg.Add(delay.Nanoseconds())
Yes, It can be -ve

2024-05-13 14:03 UTC, tbssajal commented on consensus/tendermint/backend/engine.go
> +		sealDelayBg.Add(delay.Nanoseconds())
In that case, should we add it to the metrics? We are not delaying anything, instead we are late I guess.

2024-05-13 14:10 UTC, tbssajal commented on consensus/tendermint/core/precommit.go
> +		"currentProposer", log.Lazy{Fn: func() types.CommitteeMember { return c.CommitteeSet().GetProposer(c.Round()) }},
> no, because c.Round() is only evaluated when outer function is invoked and which would be invoked on log construction.

Shouldn't we pass `c.Round()` as an argument to the wrapper `func()` for this to be true?

2024-05-13 14:12 UTC, tbssajal commented on consensus/tendermint/core/precommit.go
> +		"currentProposer", log.Lazy{Fn: func() types.CommitteeMember { return c.CommitteeSet().GetProposer(c.Round()) }},
Also, just curious, this lazy functions would invoke later, right? In that case is it possible that some data might change before the function can be invoked, like c.Round() or c.Height() for example?

2024-05-13 15:12 UTC, tbssajal requested changes

2024-05-13 15:12 UTC, tbssajal commented on metrics/buffered_gauge.go
> +		g.rIndex = g.rIndex % g.capacity
Instead of doing a mod each time, we can set `g.rIndex = 0` when we have `g.rIndex == g.capacity` and it will be the same as doing mod, because we start from `g.rIndex = 0` and we always increase it by 1.

2024-05-13 15:13 UTC, tbssajal commented on metrics/buffered_gauge.go
> +		g.rIndex = g.rIndex % g.capacity
And also because doing mod operation could be quite heavy in run time.

2024-05-13 15:18 UTC, vpiyush commented on consensus/tendermint/backend/engine.go
> +		sealDelayBg.Add(delay.Nanoseconds())
Yes, we also want to see that if we are late

2024-05-13 15:30 UTC, vpiyush commented on metrics/buffered_gauge.go
> +		g.rIndex = g.rIndex % g.capacity
I don't think we need to micro-optimize here. we will be essentially replacing  mod to a branch statement so no real gain IMO going to be worse. Having said that, It is so small that we don't really care.

2024-05-13 17:06 UTC, tbssajal approved these changes
Left two comments here: https://github.com/autonity/autonity/pull/974#discussion_r1598544199
Except that LGTM.

2024-05-14 07:42 UTC, vpiyush commented on consensus/tendermint/core/precommit.go
> +		"currentProposer", log.Lazy{Fn: func() types.CommitteeMember { return c.CommitteeSet().GetProposer(c.Round()) }},
> Shouldn't we pass `c.Round()` as an argument to the wrapper `func()` for this to be true?
> Also, just curious, this lazy functions would invoke later, right? In that case is it possible that some data might change before the function can be invoked, like c.Round() or c.Height() for example?

There are no goroutines involved here, they are invoked synchronously, what you said would be true only if they were asynchronous. it just changes the order of invokation.

2024-05-14 07:46 UTC, merged