NTN Inflation mechanism
autonity/autonity pull request #979
Opened 2024-05-09 03:13 UTC by yazzaoui

2024-05-09 11:44 UTC, tbssajal requested changes

2024-05-09 12:51 UTC, tbssajal requested changes

2024-05-09 12:51 UTC, tbssajal commented on params/protocol_contracts.go
> +		IPerm:  (*math.HexOrDecimal256)(new(big.Int).Div(new(big.Int).Mul(big.NewInt(17_328), DecimalFactor), big.NewInt(100_000*SecondsInYear))), // 17.328% AR
`inflationReserve` is already set to 40 million NTN, so `IPerm` should be just 17.328% / year, why are we multiplying it with `DecimalFactor` ?

2024-05-09 12:51 UTC, tbssajal commented on autonity/solidity/contracts/InflationController.sol
> +        if (_currentTime <= params.T) {
Not my concern but according to the [discussion](https://github.com/clearmatics/autonity-protocol/discussions/213), it looks like we are in transition period if `_lastEpochTime <= params.T` is true, otherwise it is the permanent regime.

2024-05-09 12:51 UTC, tbssajal commented on params/protocol_contracts.go
> +		IInit:  (*math.HexOrDecimal256)(new(big.Int).Div(new(big.Int).Mul(big.NewInt(75), DecimalFactor), big.NewInt(1000*SecondsInYear))),        // 7.5% AR
I guess we should not have `DecimalFactor` in any of the following following parametes, or am I missing something? If it is multiplied to keep it as ineger after division, then we should handle it in `calculateTransitionRegime` function in `InflationController.sol`, right?

2024-05-09 17:34 UTC, yazzaoui commented on params/protocol_contracts.go
> +		IPerm:  (*math.HexOrDecimal256)(new(big.Int).Div(new(big.Int).Mul(big.NewInt(17_328), DecimalFactor), big.NewInt(100_000*SecondsInYear))), // 17.328% AR
We multiply by 1e18 to conform to the `SD59x18` Solidity type used for fixed-point arithmetic by those initial parameters.

2024-05-09 20:13 UTC, yazzaoui commented on autonity/solidity/contracts/InflationController.sol
> +        if (_currentTime <= params.T) {
From my understanding we could be in a situation where the transition is happening mid-epoch so we have to account for it by splitting the calculation in two parts - maybe @fjribi can provide some feedback here ?

2024-05-10 01:45 UTC, yazzaoui commented on params/protocol_contracts.go
> +		IInit:  (*math.HexOrDecimal256)(new(big.Int).Div(new(big.Int).Mul(big.NewInt(75), DecimalFactor), big.NewInt(1000*SecondsInYear))),        // 7.5% AR
See comment above about `SD59x18` type

2024-05-10 11:22 UTC, tbssajal requested changes

2024-05-10 11:22 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +                    config.contracts.accountabilityContract.distributeRewards{value: _atnReward}(committee[i].addr);
Should we distribute `_ntnRewards` as well or is it left out on purpose?

2024-05-10 11:22 UTC, tbssajal commented on autonity/solidity/contracts/InflationController.sol
> +        if (_currentTime <= params.T) {
Another point, from my understanding, in $t < T$, here $t$ is the time passed from genesis, so it should be `_currentTime - genesisTime`, right?

2024-05-10 11:22 UTC, tbssajal commented on autonity/solidity/contracts/InflationController.sol
> +            _rate =  params.iInit + (params.iTrans - params.iInit) * _lastEpochTime / params.T;
From my understanding, the time $t$ used is this formula is the time passed after genesis, so it should be `_lastEpochTime - genesisTime`.

2024-05-10 11:22 UTC, tbssajal commented on autonity/solidity/contracts/InflationController.sol
> +            SD59x18 _lExp = (params.aE * _lastEpochTime)/params.T;
From my understanding, the time $t$ used is this formula is the time passed after genesis, so it should be `_lastEpochTime - genesisTime`.

2024-05-10 11:25 UTC, tbssajal commented on params/protocol_contracts.go
> +		IPerm:  (*math.HexOrDecimal256)(new(big.Int).Div(new(big.Int).Mul(big.NewInt(17_328), DecimalFactor), big.NewInt(100_000*SecondsInYear))), // 17.328% AR
Got it.

2024-05-10 11:55 UTC, Jason-Zhangxin-Chen commented on params/protocol_contracts.go
> +	SecondsInYear    = int64(365 * 24 * 60 * 60)
To double check if a leap year with 366 days in not consider in our case.

2024-05-10 11:57 UTC, Jason-Zhangxin-Chen reviewed
LGTM, just left a question on the board.

2024-05-10 11:59 UTC, Jason-Zhangxin-Chen commented on autonity/solidity/contracts/Autonity.sol
> +    uint256 public lastEpochTime;
Just a QQ: Why we use physical time rather than the number of blocks to compute the inflation delta?

2024-05-10 12:10 UTC, fjribi commented on autonity/solidity/contracts/InflationController.sol
> +        if (_currentTime <= params.T) {
> rom my understanding we could be in a situation where the transition is happening mid-epoch so we have to account for it by splitting the calculation in two parts - maybe @fjribi can provide some feedback here ?

Yes, indeed, see [comment](https://github.com/clearmatics/autonity-protocol/discussions/213#discussioncomment-9262617) 
>  * Besides, the discrete-time implementation of the inflation mechanism could violate the conservation law $$\forall t, \, N_t + R_t + L_t = \Gamma $$, particularly at the end dates of unlocking contracts and at the end of the transition period, potentially causing insufficient balance-like errors. A close examination of the dynamics of the Inflation Reserve $R_t$ confirms that there is no risk of the cumulative released amount exceeding the initial Inflation Reserve $\gamma$, and therefore no breach of the conservation law should occur from the dynamics of the Inflation Reserve. However, there is a risk that the amounts unlocked from the unlocking contracts could exceed the initially locked amounts $L^{(j)}_0$ at the end of the unlocking contracts ${T'}^{(j)}$. To prevent this, the last amount to be unlocked ($- \delta L(t) \cdot dt$) at $t+dt$ when $t < {T'}^{(j)} \leq t+dt$ can be replaced by the remaining locked amount $L^{(j)}(t)$.

2024-05-10 12:12 UTC, fjribi commented on autonity/solidity/contracts/InflationController.sol
> +        if (_currentTime <= params.T) {
> Another point, from my understanding, in , here  is the time passed from genesis, so it should be `_currentTime - genesisTime`, right?

Yes, $t$ = `_currentTime - genesisTime` (using the same time unit)

2024-05-10 12:30 UTC, fjribi commented on autonity/solidity/contracts/Autonity.sol
> +                    config.contracts.accountabilityContract.distributeRewards{value: _atnReward}(committee[i].addr);
In [sepecifications](https://github.com/clearmatics/autonity-protocol/discussions/213#discussioncomment-9206024) 
> * The inflation reward allocation follows the same schema as the transaction fee (BaseFee), except that inflation rewards are not subject to treasury fee taxation.

2024-05-10 12:31 UTC, fjribi commented on autonity/solidity/contracts/InflationController.sol
> +            _rate =  params.iInit + (params.iTrans - params.iInit) * _lastEpochTime / params.T;
see https://github.com/autonity/autonity/pull/979#discussion_r1596677280

2024-05-10 12:35 UTC, tbssajal commented on autonity/solidity/contracts/Autonity.sol
> +                    config.contracts.accountabilityContract.distributeRewards{value: _atnReward}(committee[i].addr);
I guess it is not treasury fee taxation, it goes to the reporter who reported the validator to jail.

2024-05-10 12:53 UTC, fjribi commented on params/protocol_contracts.go
> +	SecondsInYear    = int64(365 * 24 * 60 * 60)
Actually, we are using the following convention 

> * Time $t$ is measured in year fractions: $$t = \frac{\text{number of seconds}}{365 \times 24 \times 60 \times 60}$$ with $t=0$ at genesis. For each block, it corresponds to the difference between the current timestamp and the genesis timestamp.

It is a day count convention, meaning that `1 year = 365 * 24 * 60 * 60`, (we can use `365.25*24*60*60` instead). The same convention is used to convert annualized rates into second-based rates. Leap-year treatment is included in the $T$ parameter calculation (the same rule applies to $T^{(j)}$ and $T'^{(j)}$ as in [specifications](https://github.com/clearmatics/autonity-protocol/discussions/213#discussioncomment-9206024)). For instance, if we are targeting a particular start date-time and transition date-time, that includes a leap-year additional day, the time difference in seconds will include additional that leap-year day. Example, T = (365 +365 +365 + 366) * 24*60*60 / (  * 24*60*60) => T = 4.002739726 years or T = (365 +365 +365 + 366) * 24*60*60 in seconds (actual parameter to set in the contract code)

This avoids any particular treatment of leap years in the code it self.

Does this answer your question?

2024-05-10 13:27 UTC, fjribi commented on autonity/solidity/contracts/Autonity.sol
> +    uint256 public lastEpochTime;
Thanks for the remark. 

First of all, note that the same convention used for inflation rate time $t$ must be applied to all related unlocking schedules; otherwise, if, for some technical reasons, we start suffering a structural block time stretching (an increase of the block time in average), we could suffer some mismatch between the inflation release schedule and unlocking schedules, such a mismatch could lead to a breach in the conservation law and discontinuity of inflation rate function.

Although it is possible and easier to use block heights for all schedules, we prefer using the timestamp-based approach, mainly for the following reasons:
- If we use absolute dates for "contractual" unlocking schedules and transition dates, and we start suffering a notable increase in block time we can get a large mismatch between the contractual dates and the block-height-based timing (ex if the block time realized average is 1.05 seconds instead of the theoretical target of 1 second, could leads to 18 days mismatch over one year).
- Interest rate convention standardization across the protocol. For instance, CDP Debt interest rate compounding is timestamp-based.

_Note that there are another related remarks and arguments in this issue [Interest compounding discrete or continuous](https://github.com/clearmatics/research-stabilization/issues/299)_

2024-05-10 14:22 UTC, fjribi commented on autonity/solidity/contracts/Autonity.sol
> +                    config.contracts.accountabilityContract.distributeRewards{value: _atnReward}(committee[i].addr);
My understanding is that the "rough rule" is the following: any minted but not distributed/allocated NTNs (slashed NTNs for locked stakable NTNs, suspended vesting contract NTNs, etc.) should go to the foundation treasury account. 

> I guess it is not treasury fee taxation, it goes to the reporter who reported the validator to jail.

IMO, this case could be treated as part of the reward allocation logic (neither a "non-distributed" NTN case nor a network activity taxation treasury fee); ie. apply the same existing schema for ATN reporting reward. This could offer a higher incentive for reporting faults, @rmsams, @yazzaoui what do you think?

2024-05-10 14:39 UTC, fjribi commented on params/protocol_contracts.go
> +	SecondsInYear    = int64(365 * 24 * 60 * 60)
Note that before the MainNet launch, we are supposed to have the final dates (launch date, transition date, and all unlocking schedules dates) and inflation parameters ($\tau_{\frac{1}{2}}$, $i_{\text {trans }}$, and  $i_{\text {init }}$). Therfore we can determine the $T$, $T^{(j)}$, and $T'^{(j)}$ values according to the 365 convention. We re-run the [curve analysis notebook](https://github.com/clearmatics/autonity-protocol/blob/arn-xx-inflation-mechanism/research/12/Inflation_Mechanism_Analysis-Supply_Curves.ipynb) to solve for $a_e$ and update the controller contract parameters (subject to "seconds conversion").

2024-05-10 17:23 UTC, yazzaoui commented on autonity/solidity/contracts/InflationController.sol
> +        if (_currentTime <= params.T) {
Thanks that's a good point I overlooked when I changed for the timestamp based calculation.

2024-05-13 18:45 UTC, yazzaoui commented on autonity/solidity/contracts/Autonity.sol
> +                    config.contracts.accountabilityContract.distributeRewards{value: _atnReward}(committee[i].addr);
I don't foresee any side effects, I'll add it.

2024-05-14 12:10 UTC, tbssajal requested changes

2024-05-14 12:10 UTC, tbssajal commented on autonity/solidity/contracts/InflationController.sol
> +        SD59x18 _currentEpochBlock
'Time' instead of 'Block'

2024-05-14 12:10 UTC, tbssajal commented on autonity/tests/base.go
> +		r.evm.Context.Time = new(big.Int).Add(r.evm.Context.Time, common.Big1)
I guess, modification of Context should be done before calling 'Finalize'. Otherwise the contract has access to previous block number and time, right?

2024-05-14 12:57 UTC, yazzaoui commented on autonity/tests/base.go
> +		r.evm.Context.Time = new(big.Int).Add(r.evm.Context.Time, common.Big1)
This is fine? This is just reflecting that all previous operations on the state are accounted for the yet to be finalized block. It's the same thing we're doing when the chain is running for real.

2024-05-14 15:34 UTC, tbssajal commented on autonity/tests/base.go
> +		r.evm.Context.Time = new(big.Int).Add(r.evm.Context.Time, common.Big1)
I am not sure what is the issue then, but there is something wrong. Like if you run `r.waitNextEpoch()` no matter how many times, you will be still at block 30 (epoch period = 30).

2024-05-14 15:45 UTC, tbssajal commented on autonity/tests/base.go
> +		r.evm.Context.Time = new(big.Int).Add(r.evm.Context.Time, common.Big1)
My point is that contract function should get the information of the block beign mined when they access `block.number` or `block.timestamp`, so context should be updated before function is called. And I tested with truffle and looks like the claim is true. If you update context before calling Finalize, then the problem I just mentioned about `r.waitNextEpoch()` gets fixed.

2024-05-14 15:54 UTC, tbssajal commented on autonity/tests/base.go
> +		r.evm.Context.Time = new(big.Int).Add(r.evm.Context.Time, common.Big1)
Or I am missing the problem here I guess.

2024-05-14 16:32 UTC, tbssajal approved these changes
LGTM Except these comments: https://github.com/autonity/autonity/pull/979#discussion_r1600255648

2024-05-14 18:27 UTC, merged

2024-05-14 18:27 UTC, yazzaoui commented
Merging @tbssajal, I managed to fix a bunch of tests but there is still a few ones broken in the truffle probably due to the accounting for rewards. Thanks for taking care of that :+1:

2024-05-21 21:30 UTC, fjribi commented on autonity/solidity/contracts/InflationController.sol
> +            SD59x18 _lExp = (params.aE * _lastEpochTime)/params.T;
@yazzaoui, @tbssajal, there's no way to avoid testing params.aE == 0 each time, using a conditional compilation (pre-processing) as we know at inception the value once for all ?

2024-05-21 22:02 UTC, yazzaoui commented on autonity/solidity/contracts/InflationController.sol
> +            SD59x18 _lExp = (params.aE * _lastEpochTime)/params.T;
Not possible. I can make the adjustment on the contract logic once we know the value of params.aE.