Cache custom
autonity/autonity pull request #980
Opened 2024-05-09 09:32 UTC by vpiyush

- Introduced a fixed size cache
- peer known message cache is encapsulated in peer object now
- message subscription in core is changed to a buffered channel

2024-05-13 10:40 UTC, vpiyush commented
Fixes #947

2024-05-14 14:52 UTC, tbssajal reviewed
Just some comments, maybe I don't understand the logic of evictEntries function. Could you please explain a bit on that @vpiyush ?

2024-05-14 14:52 UTC, tbssajal commented on common/fixsizecache/cache.go
> +				if i == b.head {
I think it should be before the above if, because head has no element when not full.

2024-05-14 14:52 UTC, tbssajal commented on common/fixsizecache/cache.go
> +			for i = (b.tail - 1 + len(b.entries)) % len(b.entries); ; i = (i - 1 + len(b.entries)) % len(b.entries) {
The entry at tail is the oldest and the entry at (head-1) is the newest right? Then, I guess you should just start from tail and increase i by 1 and stop when i == head or current item has not expired as done in the following else. In current implementation, the first item is the newest one, right? Then it will remove all elements (which is correct) or break immediately (which is incorrect).

2024-05-14 14:52 UTC, tbssajal commented on common/fixsizecache/cache.go
> +				} else {
I guess this is wrong because the logic will enter this block `if b.entries[i].active == false`, but I was assuming you want to enter here only `if time.Since(b.entries[i].timestamp) <= c.evictionTime`

2024-05-14 14:52 UTC, tbssajal commented on common/fixsizecache/cache.go
> +			for i = (b.tail - 1 + len(b.entries)) % len(b.entries); ; i = (i - 1 + len(b.entries)) % len(b.entries) {
Although I might be wrong here.

2024-05-14 14:52 UTC, tbssajal commented on common/fixsizecache/cache.go
> +				if b.entries[i].active && time.Since(b.entries[i].timestamp) > c.evictionTime {
Don't we want to break `if time.Since(b.entries[i].timestamp) <= c.evictionTime` ? Otherwise when not full, we will always iterate the full bucket and will have `b.tail = b.head` at then end. Or maybe I don't understand the logic of evictEntries function.

2024-05-14 17:13 UTC, vpiyush commented
> Just some comments, maybe I don't understand the logic of evictEntries function. Could you please explain a bit on that @vpiyush ?

This was actually unused code for our use case, So i have removed it. I realized that it doesn't make sense to have an time based removal for a fixed size cache because we don't really free any memory. It just unnecessary creates noise.

2024-05-15 11:57 UTC, tbssajal requested changes

2024-05-15 11:57 UTC, tbssajal commented on common/fixsizecache/cache.go
> +			for j := i; j != b.index; j = (j + 1) % len(b.entries) {
Instead of doing a loop, consider just swaping two entries. Not sure if it is a good idea though. But what we can do is if `i != b.index` then swap the entries at `i` and `b.index-1`. And then we can decrease `b.index` by 1. Reading only cache.go, it looks like the order of the entries in a bucket does not matter, so it would be efficient.

2024-05-15 11:57 UTC, tbssajal commented on common/fixsizecache/cache.go
> +			for j := i; j != b.index; j = (j + 1) % len(b.entries) {
In case we have to keep the loop, some comments:
Here `j != b.index` works if `i == b.index` or the list of entries has not been full yet. But if the list has been full and it has become a circular list, then there is a problem in the behaviour I guess. Because the list is full, by removing one element, the list is not full anymore. So when a new entry will be added, you don't need to replace any old entry. Here you are shifting everyting including `b.index` and then decreasing `b.index` by 1. Note that the entry at `b.index` is active, but entry at `b.index+1` is inactive now. But when a new entry will be added, it will replace the active entry at `b.index`, which is unnecessary because we have an inactive entry at `b.index+1`. IMO the way to handle it will be to check `j != b.index && (j + 1) % len(b.entries) != b.index` in the for loop. Basically shifting all entries from `i` to `b.index-1` (excluding `b.index`) and decrease `b.index` by 1. This way we will have an inactive entry at `b.index`

2024-05-15 11:57 UTC, tbssajal commented on common/fixsizecache/cache.go
> +			for j := i; j != b.index; j = (j + 1) % len(b.entries) {
I didn't test the claim, let me know if I made any mistake there.

2024-05-15 14:07 UTC, vpiyush commented on common/fixsizecache/cache.go
> +			for j := i; j != b.index; j = (j + 1) % len(b.entries) {
> Instead of doing a loop, consider just swaping two entries. Not sure if it is a good idea though. But what we can do is if `i != b.index` then swap the entries at `i` and `b.index-1` and also decrease `b.index` by 1. If `i == b.index`, no need to swap anything or decrease `b.index`. Reading only cache.go, it looks like the order of the entries in a bucket does not matter, so it would be efficient.

Actually Order still matters, least recent entries are overwritten first when cricular buffer is full.

2024-05-16 12:21 UTC, tbssajal requested changes

2024-05-16 20:36 UTC, vpiyush commented on consensus/acn/protocol/handler.go
> -	if metrics.Enabled {
these are tracked in backend handler now

2024-05-16 20:42 UTC, vpiyush commented on common/fixsizecache/helpers.go
> +func isPrime(n int) bool {
I believe this is overkill for the situation. It's merely a helper to get a prime number when initializing the cache, which the user could also hardcode. Additionally, peer connections are infrequent, so this won't have any significant impact in the grand scheme of things.

2024-05-16 20:50 UTC, vpiyush commented on common/fixsizecache/helpers.go
> +	for i, k := range key {
I think we would get better distribution when we sum all bytes. It shouldn't depend on the size of the output.

2024-05-16 20:50 UTC, vpiyush commented on common/fixsizecache/cache.go
> +			b.index = (b.index - 1 + len(b.entries)) % len(b.entries)
Yeah. this is correct

2024-05-16 20:51 UTC, vpiyush commented on common/fixsizecache/cache.go
> +	keys := make([]T, 0, c.Size())
nope this isn't supposed to be there

2024-05-16 20:52 UTC, vpiyush commented on common/fixsizecache/helpers.go
> +		return 0
yeah, we can make it 2.

2024-05-20 09:29 UTC, tbssajal requested changes

2024-05-20 09:29 UTC, tbssajal commented on common/fixsizecache/helpers.go
> +	for i, k := range key {
I mean to say that int is only 8 bytes long, so the result will be same if you break the loop after the first 8 bytes. The remaining bytes are shifted at least 64 bits, so they will overflow and not add to the result. If you want to take all the bytes in result, consider doing circular shift by writing `result |= int(k) << ((i%8) * 8)`

2024-05-20 09:29 UTC, tbssajal commented on common/fixsizecache/helpers.go
> +	for i, k := range key {
But I have a concern with circular shift. If you want to do circular shift, I guess it is better to do bitwise xor instead of bitwise or. Because, in case of or, for a single bit, `c = a | b`, there is 75% chance for `c = 1` and 25% chance for `c = 0`. And if c becomes 1, it will always  remain 1. So there won't be much diversity, most bits will be 1. But if you do bitwise xor, `c = a ^ b`, it has equal chance to be 0 or 1. And it will not remain the same like bitwise or. So the result will be somewhat more random than bitwise or, if that's what is needed here. If you don't do any circular shift, then doing xor / or gives same result, so it is fine.

2024-05-20 09:29 UTC, tbssajal commented on common/fixsizecache/helpers.go
> +	for i, k := range key {
I guess this function will be invoked most of the times when cache is used. So I guess, for the sake of efficiency, maybe consider replacing the operations with bitwise operation where possible. Like replace `x * 8` with `x << 3` [because $x * 2^p = x << p$ ] and `x % 8` with `x & 7` [because $x \  \\% \  2^p = x \ \\& \  (2^p - 1)$ ]. Just a small note from me. You can decide if it is worth doing or not of course.

2024-05-20 11:25 UTC, vpiyush commented on common/fixsizecache/helpers.go
> +	for i, k := range key {
I see the point and it's essential that we do utilize all bytes in the input to calculate the sum, I tried well established hash function for this specific purpose and they are very fast comparable and even better sometimes to the naive implementation, So i am gonna switch to that.

2024-05-22 04:25 UTC, yazzaoui approved these changes
I didn't review the cache code in depth but everything else seems fine. LGTM!

2024-05-22 10:29 UTC, tbssajal approved these changes
LGTM

2024-05-23 08:05 UTC, merged