Accountablity base on msg aggregation
autonity/autonity pull request #986
Opened 2024-05-22 09:17 UTC by Jason-Zhangxin-Chen

This PR presents the new fault detector base on the message aggregation feature, the unit test and moudule test were finished.

2024-05-22 16:42 UTC, lorenzo-dev1 requested changes
Some change requests.

Additionally I think that we need some new tests for:
1. Making sure that the fault detector works well with aggregates and manages to raise and verify proofs even if we feed only aggregates to it.
2. Making sure no-one can abuse the system through the new aggregate mechanics (e.g. inserting messages from validator A but the index in the proof is from validator B).

But it is better to leave those to a separate PR, so that we can merge this one and start to fix the e2e tests and as well do performance testing with the FD enabled.

2024-05-22 16:42 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/contracts.go
> -	return nil
I guess this past version that we had in the client was broken? Looking at it now, it doesn't make sense

2024-05-22 16:42 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/contracts.go
> +func validMisbehaviourOfEquivocation(proof *Proof, committee types.Committee) bool {
I think we should add a check that `len(proof.Evidences) == 1`, otherwise just discard the proof

2024-05-22 16:42 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/contracts.go
> +		if msg1.H() == msg2.H() && msg1.R() == msg2.R() && msg1.Signer() == msg2.Signer() &&
This might work but tbh I would prefer just checking that the two proposals have either:
1. different valid round
2. different value

Instead of relying on the `msg.Hash()`. It is not reliable anymore for equivocation

2024-05-22 16:42 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/contracts.go
> +		if vote1.H() == vote2.H() && vote1.R() == vote2.R() && msg1.Hash() != vote2.Hash() {
This will not work, we have to check that the values of the vote are different.

We could have two votes for same value but with different hashes (if the `signers` objects are different).

2024-05-23 07:37 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/msg_store.go
> +	signer := signers[0]
I was trying to omit the providing of signer when calling this function, now I turn to use a pointer for it. Resolved in 466e794e5bdfde4325931a7cd0181ff96d3119e6

2024-05-23 07:37 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/msg_store_test.go
> +		assert.Equal(t, true, votes[0].(message.Vote).Signers().Contains(proposerIdx))
Resolved in 466e794e5bdfde4325931a7cd0181ff96d3119e6

2024-05-23 08:06 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +			innocenceProof, err := fd.innocenceProof(decodedProof, committee)
Resolved in 3d07fd9d959e4dd950bbaf641ccf5f0740adebe9, I thought that we just need to fetch committee from blockchain only once for the entire workfow, however your point is valid, now I fetch the committee outside of it, by passing it, the workflow now can just share it to the end.

2024-05-23 08:06 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +func (fd *FaultDetector) innocenceProofPVN(c *Proof, committee types.Committee) (*autonity.AccountabilityEvent, error) {
Resolved in 3d07fd9d959e4dd950bbaf641ccf5f0740adebe9 as I explained in the last comment.

2024-05-23 08:14 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/core/msg_store.go
>  func GetStore[T any, PT interface {
We don't need to update this function yet. It was used for proposal query and the structure of the msg store remains the same.

2024-05-23 08:57 UTC, lorenzo-dev1 commented on consensus/tendermint/accountability/fault_detector.go
> +			innocenceProof, err := fd.innocenceProof(decodedProof, committee)
I see, it shouldn't be a problem because the header should be cached in memory already. However if we see it is a performance issue when profiling we can revert back to something similar to this.

2024-05-23 09:05 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +	fd.msgStore.Save(proposal, nil)
My concern was, it will introduce chain dependency in msg store, and slow it down by fetching committee for each msg.

2024-05-23 09:08 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +		panic("Wrong my code for accountability")
Yes, resloved in 73dc605c333a4a15c854fd9b5e66cd147f6b8512

2024-05-23 09:08 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
>  		prevote := p
Resloved in 73dc605c333a4a15c854fd9b5e66cd147f6b8512

2024-05-23 09:08 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +			// Due to the for loop there must be at least one preVote.
resloved in 73dc605c333a4a15c854fd9b5e66cd147f6b8512

2024-05-23 09:09 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +				continue prevotesLoop // we have no corresponding proposal, so we cannot check new and old prevote rules
Yes, this is valid. All the signers should be checked. resloved in 73dc605c333a4a15c854fd9b5e66cd147f6b8512

2024-05-23 09:10 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/fault_detector.go
> +	singersLoop:
resloved in 73dc605c333a4a15c854fd9b5e66cd147f6b8512

2024-05-23 11:16 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +func validMisbehaviourOfEquivocation(proof *Proof, committee types.Committee) bool {
checking with == 1 is more strict, I will do that.

2024-05-23 12:01 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/innocence_proof_handler.go
> +	}
Restored as they were in 4e8598c65911b815185bf2bb536e0fdfae410e0b

2024-05-23 12:01 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/innocence_proof_handler.go
> +	}
Restored as they were in 4e8598c65911b815185bf2bb536e0fdfae410e0b

2024-05-23 12:02 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/innocence_proof_handler.go
> -	}
Restored as they were in 4e8598c65911b815185bf2bb536e0fdfae410e0b

2024-05-23 12:02 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +func verifyProofSignatures(chain ChainContext, p *Proof) (types.Committee, error) {
Restored as they were in 4e8598c65911b815185bf2bb536e0fdfae410e0b

2024-05-23 12:02 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> -}
Restored as they were in 4e8598c65911b815185bf2bb536e0fdfae410e0b

2024-05-23 12:04 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +		if msg1.H() == msg2.H() && msg1.R() == msg2.R() && msg1.Signer() == msg2.Signer() &&
Thank you for this reminder, I didn't notice the changes of msh hash with aggregation. Resolved in  4e8598c65911b815185bf2bb536e0fdfae410e0b

2024-05-23 12:04 UTC, Jason-Zhangxin-Chen commented on consensus/tendermint/accountability/contracts.go
> +		if vote1.H() == vote2.H() && vote1.R() == vote2.R() && msg1.Hash() != vote2.Hash() {
Thank you for this reminder, I didn't notice the changes of msh hash with aggregation. Resolved in https://github.com/autonity/autonity/commit/4e8598c65911b815185bf2bb536e0fdfae410e0b

2024-05-23 12:55 UTC, lorenzo-dev1 approved these changes
LGTM, thanks a lot @Jason-Zhangxin-Chen  

if you agree let's merge this into the `bls-integration` branch so I can fix the e2e tests

2024-05-23 13:27 UTC, merged